-- ============================================================
-- BIBLE APPLICATION DATABASE SCHEMA
-- Compatible with Supabase PostgreSQL
-- ============================================================

-- 1. Bible Books Table
CREATE TABLE IF NOT EXISTS public.bible_books (
  id INT PRIMARY KEY,
  book_number INT NOT NULL UNIQUE,
  testament VARCHAR(2) NOT NULL CHECK (testament IN ('OT', 'NT')),
  name_en VARCHAR(100) NOT NULL,
  name_ta VARCHAR(150) NOT NULL,
  code VARCHAR(10) NOT NULL,
  total_chapters INT NOT NULL DEFAULT 1
);

-- 2. Bible Verses Table
CREATE TABLE IF NOT EXISTS public.bible_verses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  book_id INT NOT NULL REFERENCES public.bible_books(id) ON DELETE CASCADE,
  chapter INT NOT NULL,
  verse INT NOT NULL,
  text_en TEXT NOT NULL DEFAULT '',
  text_ta TEXT NOT NULL DEFAULT '',
  CONSTRAINT unique_book_chapter_verse UNIQUE (book_id, chapter, verse)
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_bible_verses_lookup ON public.bible_verses(book_id, chapter, verse);
CREATE INDEX IF NOT EXISTS idx_bible_verses_chapter ON public.bible_verses(book_id, chapter);
CREATE INDEX IF NOT EXISTS idx_bible_verses_fts_en ON public.bible_verses USING gin(to_tsvector('english', text_en));

-- 3. User Bookmarks Table
CREATE TABLE IF NOT EXISTS public.user_bookmarks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  book_id INT NOT NULL REFERENCES public.bible_books(id) ON DELETE CASCADE,
  chapter INT NOT NULL,
  verse INT NOT NULL,
  language VARCHAR(5) NOT NULL DEFAULT 'en',
  note TEXT DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_bookmarks_lookup ON public.user_bookmarks(book_id, chapter, verse);

-- 4. User Reading History Table
CREATE TABLE IF NOT EXISTS public.user_reading_history (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  book_id INT NOT NULL REFERENCES public.bible_books(id) ON DELETE CASCADE,
  chapter INT NOT NULL,
  verse INT NOT NULL DEFAULT 1,
  language VARCHAR(5) NOT NULL DEFAULT 'en',
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_reading_history_updated ON public.user_reading_history(updated_at DESC);

-- Enable Row Level Security (RLS)
ALTER TABLE public.bible_books ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bible_verses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_bookmarks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_reading_history ENABLE ROW LEVEL SECURITY;

-- Allow public read access to Bible data
CREATE POLICY "Allow public read access to bible_books" ON public.bible_books FOR SELECT USING (true);
CREATE POLICY "Allow public read access to bible_verses" ON public.bible_verses FOR SELECT USING (true);

-- Allow public insert/select/delete on bookmarks & history for personal app usage
CREATE POLICY "Allow anonymous read bookmarks" ON public.user_bookmarks FOR SELECT USING (true);
CREATE POLICY "Allow anonymous insert bookmarks" ON public.user_bookmarks FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow anonymous delete bookmarks" ON public.user_bookmarks FOR DELETE USING (true);

CREATE POLICY "Allow anonymous read history" ON public.user_reading_history FOR SELECT USING (true);
CREATE POLICY "Allow anonymous insert/update history" ON public.user_reading_history FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow anonymous update history" ON public.user_reading_history FOR UPDATE USING (true);
