import { StudioTemplate, StudioLayer, TextLayer, ShapeLayer, ElementLayer } from './types';

export const CANVAS_PRESETS = [
  { id: '1:1' as const, name: 'Square Post', nameTa: '1:1 சதுரம்', sub: 'Instagram / WhatsApp DP', width: 1080, height: 1080, icon: '⬛' },
  { id: '9:16' as const, name: 'Story / Reel', nameTa: '9:16 ஸ்டோரி', sub: 'WhatsApp Status / Reels', width: 1080, height: 1920, icon: '📱' },
  { id: '4:5' as const, name: 'Feed Portrait', nameTa: '4:5 போர்ட்ரெய்ட்', sub: 'Instagram Portrait Feed', width: 1080, height: 1350, icon: '🖼' },
  { id: '16:9' as const, name: 'Landscape Banner', nameTa: '16:9 திரையகம்', sub: 'YouTube / Projection', width: 1920, height: 1080, icon: '🖥' },
];

export const TAMIL_FONTS_LIST = [
  { id: 'noto-serif', name: 'Noto Serif Tamil', nameTa: 'பாரம்பரியம் (Serif)', font: `'Noto Serif Tamil', Georgia, serif` },
  { id: 'noto-sans', name: 'Noto Sans Tamil', nameTa: 'நவீன எழுத்து (Sans)', font: `'Noto Sans Tamil', sans-serif` },
  { id: 'mukta', name: 'Mukta Malar', nameTa: 'அழகிய மலர்', font: `'Mukta Malar', 'Noto Sans Tamil', sans-serif` },
  { id: 'catamaran', name: 'Catamaran', nameTa: 'கம்பீர நடை', font: `'Catamaran', 'Noto Sans Tamil', sans-serif` },
  { id: 'kavivanar', name: 'Kavivanar Script', nameTa: 'கவிவாணர் எழுத்து', font: `'Kavivanar', cursive` },
  { id: 'baloo', name: 'Baloo Thambi', nameTa: 'தடிமன் பாலு (Rounded)', font: `'Baloo Thambi 2', sans-serif` },
  { id: 'hind', name: 'Hind Madurai', nameTa: 'மதுரை நடை', font: `'Hind Madurai', sans-serif` },
  { id: 'arima', name: 'Arima Script', nameTa: 'அரிமா கவிதை', font: `'Arima', cursive` },
];

export const ENGLISH_FONTS_LIST = [
  { id: 'cinzel', name: 'Cinzel Roman', nameTa: 'ராஜ கம்பீரம் (Cinzel)', font: `'Cinzel', Georgia, serif` },
  { id: 'playfair', name: 'Playfair Display', nameTa: 'அரண்மனை உரை (Playfair)', font: `'Playfair Display', Georgia, serif` },
  { id: 'lora', name: 'Lora Sacred', nameTa: 'வேதாகம உரை (Lora)', font: `'Lora', serif` },
  { id: 'inter', name: 'Inter Clean', nameTa: 'நவீன எழுத்து (Inter)', font: `'Inter', sans-serif` },
  { id: 'poppins', name: 'Poppins Bold', nameTa: 'நவீன வடிவம் (Poppins)', font: `'Poppins', sans-serif` },
  { id: 'caveat', name: 'Caveat Script', nameTa: 'கையொப்பம் (Caveat)', font: `'Caveat', cursive` },
];

export const STUDIO_TEMPLATES: StudioTemplate[] = [
  // 1. Golden Faith (Luxury Gold & Deep Dark)
  {
    id: 'golden-faith',
    name: 'Golden Faith',
    nameTa: 'தங்க விசுவாசம்',
    category: 'Luxury',
    thumbnailGradient: 'linear-gradient(135deg, #181206, #d97706)',
    canvasRatio: '1:1',
    background: {
      type: 'gradient',
      solidColor: '#120d04',
      gradientType: 'linear',
      gradientAngle: 145,
      gradientStops: [
        { offset: 0, color: '#0f0a02' },
        { offset: 0.55, color: '#1f1505' },
        { offset: 1, color: '#382506' }
      ],
      overlayColor: '#000000',
      overlayOpacity: 0.2,
      vignette: 45,
      grain: true,
      imageBrightness: 100,
      imageContrast: 100,
      imageSaturation: 100,
      imageBlur: 0
    },
    effects: {
      glassmorphism: true,
      frostedGlass: false,
      lightLeak: false,
      duotone: false,
      cinematicBorder: true,
      borderColor: '#fbbf24',
      borderWidth: 3
    },
    createLayers: (verseTa, verseEn, ref, w, h) => [
      {
        id: 'layer-frame',
        name: 'Gold Border Frame',
        type: 'shape',
        shapeType: 'rounded',
        x: w * 0.05,
        y: h * 0.05,
        width: w * 0.9,
        height: h * 0.9,
        rotation: 0,
        opacity: 0.7,
        visible: true,
        locked: false,
        zIndex: 1,
        fillColor: 'transparent',
        borderColor: '#fbbf24',
        borderWidth: 2,
        borderRadius: 24,
        shadowColor: '#d97706',
        shadowBlur: 14
      },
      {
        id: 'layer-symbol',
        name: 'Sacred Cross',
        type: 'element',
        elementId: 'cross-ornate',
        svgPath: 'M12 2v20M7 8h10',
        x: w * 0.5 - 20,
        y: h * 0.16,
        width: 40,
        height: 48,
        rotation: 0,
        opacity: 0.85,
        visible: true,
        locked: false,
        zIndex: 2,
        color: '#fbbf24',
        shadowColor: 'rgba(251,191,36,0.6)',
        shadowBlur: 12
      },
      {
        id: 'layer-verse-ta',
        name: 'Tamil Verse Text',
        type: 'text',
        role: 'verse-ta',
        text: verseTa || 'கர்த்தர் என் வெளிச்சமும் என் இரட்சிப்புமானவர், யாருக்குப் பயப்படுவேன்?',
        fontFamily: `'Noto Serif Tamil', Georgia, serif`,
        fontSize: Math.round(w * 0.046),
        fontWeight: '600',
        fontStyle: 'normal',
        textAlign: 'center',
        textColor: '#fef3c7',
        lineHeight: 1.7,
        letterSpacing: 0.5,
        textTransform: 'none',
        shadowColor: 'rgba(0,0,0,0.9)',
        shadowBlur: 10,
        shadowOffsetX: 0,
        shadowOffsetY: 3,
        strokeColor: '',
        strokeWidth: 0,
        hasBgBox: false,
        bgBoxColor: 'rgba(0,0,0,0.4)',
        bgBoxPadding: 16,
        bgBoxRadius: 16,
        x: w * 0.1,
        y: h * 0.32,
        width: w * 0.8,
        height: h * 0.35,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 3
      },
      {
        id: 'layer-verse-en',
        name: 'English Translation',
        type: 'text',
        role: 'verse-en',
        text: verseEn ? `"${verseEn}"` : '"The Lord is my light and my salvation; whom shall I fear?"',
        fontFamily: `'Lora', serif`,
        fontSize: Math.round(w * 0.026),
        fontWeight: '400',
        fontStyle: 'italic',
        textAlign: 'center',
        textColor: '#e2e8f0',
        lineHeight: 1.5,
        letterSpacing: 0.3,
        textTransform: 'none',
        shadowColor: 'rgba(0,0,0,0.8)',
        shadowBlur: 6,
        shadowOffsetX: 0,
        shadowOffsetY: 2,
        strokeColor: '',
        strokeWidth: 0,
        hasBgBox: false,
        bgBoxColor: '',
        bgBoxPadding: 0,
        bgBoxRadius: 0,
        x: w * 0.12,
        y: h * 0.67,
        width: w * 0.76,
        height: h * 0.14,
        rotation: 0,
        opacity: 0.9,
        visible: !!verseEn,
        locked: false,
        zIndex: 4
      },
      {
        id: 'layer-ref',
        name: 'Scripture Reference',
        type: 'text',
        role: 'reference',
        text: `— ${ref || 'சங்கீதம் 27:1'} —`,
        fontFamily: `'Cinzel', 'Noto Serif Tamil', serif`,
        fontSize: Math.round(w * 0.032),
        fontWeight: '700',
        fontStyle: 'normal',
        textAlign: 'center',
        textColor: '#fbbf24',
        lineHeight: 1.3,
        letterSpacing: 2,
        textTransform: 'uppercase',
        shadowColor: 'rgba(217,119,6,0.6)',
        shadowBlur: 8,
        shadowOffsetX: 0,
        shadowOffsetY: 2,
        hasBgBox: true,
        bgBoxColor: 'rgba(251,191,36,0.12)',
        bgBoxPadding: 8,
        bgBoxRadius: 99,
        strokeColor: '',
        strokeWidth: 0,
        x: w * 0.25,
        y: h * 0.83,
        width: w * 0.5,
        height: 48,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 5
      }
    ]
  },

  // 2. Cinematic Worship (Deep Indigo & Purple Glow)
  {
    id: 'cinematic-worship',
    name: 'Cinematic Worship',
    nameTa: 'ஆராதனை ஒளி',
    category: 'Cinematic',
    thumbnailGradient: 'linear-gradient(135deg, #090919, #6d28d9)',
    canvasRatio: '9:16',
    background: {
      type: 'gradient',
      solidColor: '#070614',
      gradientType: 'linear',
      gradientAngle: 180,
      gradientStops: [
        { offset: 0, color: '#090518' },
        { offset: 0.45, color: '#170c36' },
        { offset: 1, color: '#04020a' }
      ],
      overlayColor: '#7c3aed',
      overlayOpacity: 0.15,
      vignette: 55,
      grain: true,
      imageBrightness: 100,
      imageContrast: 100,
      imageSaturation: 100,
      imageBlur: 0
    },
    effects: {
      glassmorphism: true,
      frostedGlass: true,
      lightLeak: true,
      duotone: false,
      cinematicBorder: false,
      borderColor: '#a78bfa',
      borderWidth: 1
    },
    createLayers: (verseTa, verseEn, ref, w, h) => [
      {
        id: 'layer-glass-card',
        name: 'Frosted Glass Backdrop',
        type: 'shape',
        shapeType: 'rounded',
        x: w * 0.08,
        y: h * 0.26,
        width: w * 0.84,
        height: h * 0.52,
        rotation: 0,
        opacity: 0.88,
        visible: true,
        locked: false,
        zIndex: 1,
        fillColor: 'rgba(255,255,255,0.06)',
        borderColor: 'rgba(255,255,255,0.18)',
        borderWidth: 1.5,
        borderRadius: 28,
        shadowColor: 'rgba(0,0,0,0.6)',
        shadowBlur: 24
      },
      {
        id: 'layer-verse-ta',
        name: 'Tamil Verse Text',
        type: 'text',
        role: 'verse-ta',
        text: verseTa || 'நான் உன்னை விட்டு விலகுவதுமில்லை, உன்னைக் கைவிடுவதுமில்லை.',
        fontFamily: `'Noto Serif Tamil', serif`,
        fontSize: Math.round(w * 0.052),
        fontWeight: '600',
        fontStyle: 'normal',
        textAlign: 'center',
        textColor: '#f8fafc',
        lineHeight: 1.8,
        letterSpacing: 0.5,
        textTransform: 'none',
        shadowColor: 'rgba(0,0,0,0.9)',
        shadowBlur: 14,
        shadowOffsetX: 0,
        shadowOffsetY: 4,
        strokeColor: '',
        strokeWidth: 0,
        hasBgBox: false,
        bgBoxColor: '',
        bgBoxPadding: 0,
        bgBoxRadius: 0,
        x: w * 0.12,
        y: h * 0.33,
        width: w * 0.76,
        height: h * 0.26,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 2
      },
      {
        id: 'layer-verse-en',
        name: 'English Translation',
        type: 'text',
        role: 'verse-en',
        text: verseEn ? `"${verseEn}"` : '"I will never leave you nor forsake you."',
        fontFamily: `'Lora', serif`,
        fontSize: Math.round(w * 0.034),
        fontWeight: '400',
        fontStyle: 'italic',
        textAlign: 'center',
        textColor: '#c4b5fd',
        lineHeight: 1.6,
        letterSpacing: 0.5,
        textTransform: 'none',
        shadowColor: 'rgba(0,0,0,0.7)',
        shadowBlur: 8,
        shadowOffsetX: 0,
        shadowOffsetY: 2,
        hasBgBox: false,
        bgBoxColor: '',
        bgBoxPadding: 0,
        bgBoxRadius: 0,
        strokeColor: '',
        strokeWidth: 0,
        x: w * 0.12,
        y: h * 0.60,
        width: w * 0.76,
        height: h * 0.12,
        rotation: 0,
        opacity: 0.95,
        visible: true,
        locked: false,
        zIndex: 3
      },
      {
        id: 'layer-ref',
        name: 'Bible Reference',
        type: 'text',
        role: 'reference',
        text: `[ ${ref || 'யோசுவா 1:5'} ]`,
        fontFamily: `'Cinzel', sans-serif`,
        fontSize: Math.round(w * 0.036),
        fontWeight: '700',
        fontStyle: 'normal',
        textAlign: 'center',
        textColor: '#a78bfa',
        lineHeight: 1.4,
        letterSpacing: 2.5,
        textTransform: 'uppercase',
        shadowColor: 'rgba(124,58,237,0.5)',
        shadowBlur: 10,
        shadowOffsetX: 0,
        shadowOffsetY: 2,
        hasBgBox: false,
        bgBoxColor: '',
        bgBoxPadding: 0,
        bgBoxRadius: 0,
        strokeColor: '',
        strokeWidth: 0,
        x: w * 0.2,
        y: h * 0.73,
        width: w * 0.6,
        height: 50,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 4
      }
    ]
  },

  // 3. Minimal White (Pristine Editorial Typography)
  {
    id: 'minimal-white',
    name: 'Minimal White',
    nameTa: 'தூய வெண்மை',
    category: 'Minimal',
    thumbnailGradient: 'linear-gradient(135deg, #f8fafc, #e2e8f0)',
    canvasRatio: '1:1',
    background: {
      type: 'solid',
      solidColor: '#ffffff',
      gradientType: 'linear',
      gradientAngle: 0,
      gradientStops: [],
      overlayColor: '#000000',
      overlayOpacity: 0,
      vignette: 0,
      grain: false,
      imageBrightness: 100,
      imageContrast: 100,
      imageSaturation: 100,
      imageBlur: 0
    },
    effects: {
      glassmorphism: false,
      frostedGlass: false,
      lightLeak: false,
      duotone: false,
      cinematicBorder: false,
      borderColor: '#e2e8f0',
      borderWidth: 1
    },
    createLayers: (verseTa, verseEn, ref, w, h) => [
      {
        id: 'layer-accent-bar',
        name: 'Top Accent Line',
        type: 'shape',
        shapeType: 'rect',
        x: w * 0.44,
        y: h * 0.18,
        width: w * 0.12,
        height: 4,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 1,
        fillColor: '#0f172a',
        borderColor: 'transparent',
        borderWidth: 0,
        borderRadius: 99,
        shadowColor: 'transparent',
        shadowBlur: 0
      },
      {
        id: 'layer-verse-ta',
        name: 'Tamil Verse Text',
        type: 'text',
        role: 'verse-ta',
        text: verseTa || 'தேவன் நமக்கு அடைக்கலமும் பெலனும், ஆபத்துக்காலத்தில் அனுகூலமான துணையுமானவர்.',
        fontFamily: `'Noto Serif Tamil', Georgia, serif`,
        fontSize: Math.round(w * 0.046),
        fontWeight: '500',
        fontStyle: 'normal',
        textAlign: 'center',
        textColor: '#0f172a',
        lineHeight: 1.85,
        letterSpacing: 0.3,
        textTransform: 'none',
        shadowColor: 'transparent',
        shadowBlur: 0,
        shadowOffsetX: 0,
        shadowOffsetY: 0,
        strokeColor: '',
        strokeWidth: 0,
        hasBgBox: false,
        bgBoxColor: '',
        bgBoxPadding: 0,
        bgBoxRadius: 0,
        x: w * 0.12,
        y: h * 0.28,
        width: w * 0.76,
        height: h * 0.36,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 2
      },
      {
        id: 'layer-verse-en',
        name: 'English Translation',
        type: 'text',
        role: 'verse-en',
        text: verseEn ? `"${verseEn}"` : '"God is our refuge and strength, an ever-present help in trouble."',
        fontFamily: `'Lora', serif`,
        fontSize: Math.round(w * 0.026),
        fontWeight: '400',
        fontStyle: 'normal',
        textAlign: 'center',
        textColor: '#475569',
        lineHeight: 1.6,
        letterSpacing: 0.3,
        textTransform: 'none',
        shadowColor: 'transparent',
        shadowBlur: 0,
        shadowOffsetX: 0,
        shadowOffsetY: 0,
        hasBgBox: false,
        bgBoxColor: '',
        bgBoxPadding: 0,
        bgBoxRadius: 0,
        strokeColor: '',
        strokeWidth: 0,
        x: w * 0.14,
        y: h * 0.66,
        width: w * 0.72,
        height: h * 0.12,
        rotation: 0,
        opacity: 0.9,
        visible: true,
        locked: false,
        zIndex: 3
      },
      {
        id: 'layer-ref',
        name: 'Bible Reference',
        type: 'text',
        role: 'reference',
        text: `— ${ref || 'சங்கீதம் 46:1'} —`,
        fontFamily: `'Playfair Display', serif`,
        fontSize: Math.round(w * 0.028),
        fontWeight: '700',
        fontStyle: 'normal',
        textAlign: 'center',
        textColor: '#0f172a',
        lineHeight: 1.4,
        letterSpacing: 2,
        textTransform: 'uppercase',
        shadowColor: 'transparent',
        shadowBlur: 0,
        shadowOffsetX: 0,
        shadowOffsetY: 0,
        hasBgBox: false,
        bgBoxColor: '',
        bgBoxPadding: 0,
        bgBoxRadius: 0,
        strokeColor: '',
        strokeWidth: 0,
        x: w * 0.25,
        y: h * 0.81,
        width: w * 0.5,
        height: 40,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 4
      }
    ]
  },

  // 4. Sunset Prayer (Warm Amber Gradient)
  {
    id: 'sunset-prayer',
    name: 'Sunset Prayer',
    nameTa: 'அந்தி ஜெபம்',
    category: 'Warm',
    thumbnailGradient: 'linear-gradient(135deg, #b45309, #dc2626)',
    canvasRatio: '4:5',
    background: {
      type: 'gradient',
      solidColor: '#1c0e06',
      gradientType: 'linear',
      gradientAngle: 150,
      gradientStops: [
        { offset: 0, color: '#f59e0b' },
        { offset: 0.45, color: '#ea580c' },
        { offset: 1, color: '#b91c1c' }
      ],
      overlayColor: '#000000',
      overlayOpacity: 0.35,
      vignette: 40,
      grain: true,
      imageBrightness: 100,
      imageContrast: 100,
      imageSaturation: 100,
      imageBlur: 0
    },
    effects: {
      glassmorphism: true,
      frostedGlass: false,
      lightLeak: false,
      duotone: false,
      cinematicBorder: true,
      borderColor: '#fef08a',
      borderWidth: 1.5
    },
    createLayers: (verseTa, verseEn, ref, w, h) => [
      {
        id: 'layer-verse-ta',
        name: 'Tamil Verse Text',
        type: 'text',
        role: 'verse-ta',
        text: verseTa || 'அவர் காலையில்தோறும் புதியவைகள்; உமது உண்மை பெரிதாயிருக்கிறது.',
        fontFamily: `'Noto Serif Tamil', serif`,
        fontSize: Math.round(w * 0.048),
        fontWeight: '600',
        fontStyle: 'normal',
        textAlign: 'center',
        textColor: '#ffffff',
        lineHeight: 1.75,
        letterSpacing: 0.5,
        textTransform: 'none',
        shadowColor: 'rgba(0,0,0,0.9)',
        shadowBlur: 14,
        shadowOffsetX: 0,
        shadowOffsetY: 3,
        strokeColor: '',
        strokeWidth: 0,
        hasBgBox: false,
        bgBoxColor: '',
        bgBoxPadding: 0,
        bgBoxRadius: 0,
        x: w * 0.1,
        y: h * 0.30,
        width: w * 0.8,
        height: h * 0.32,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 1
      },
      {
        id: 'layer-ref',
        name: 'Bible Reference',
        type: 'text',
        role: 'reference',
        text: `• ${ref || 'புலம்பல் 3:23'} •`,
        fontFamily: `'Cinzel', serif`,
        fontSize: Math.round(w * 0.032),
        fontWeight: '700',
        fontStyle: 'normal',
        textAlign: 'center',
        textColor: '#fef08a',
        lineHeight: 1.3,
        letterSpacing: 2,
        textTransform: 'uppercase',
        shadowColor: 'rgba(0,0,0,0.8)',
        shadowBlur: 8,
        shadowOffsetX: 0,
        shadowOffsetY: 2,
        hasBgBox: true,
        bgBoxColor: 'rgba(0,0,0,0.3)',
        bgBoxPadding: 10,
        bgBoxRadius: 99,
        strokeColor: '',
        strokeWidth: 0,
        x: w * 0.25,
        y: h * 0.72,
        width: w * 0.5,
        height: 48,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 2
      }
    ]
  },

  // 5. Ocean Peace (Serene Navy Teal Deep Waters)
  {
    id: 'ocean-peace',
    name: 'Ocean Peace',
    nameTa: 'ஆழி சமாதானம்',
    category: 'Serene',
    thumbnailGradient: 'linear-gradient(135deg, #082f49, #0284c7)',
    canvasRatio: '1:1',
    background: {
      type: 'gradient',
      solidColor: '#031a29',
      gradientType: 'linear',
      gradientAngle: 160,
      gradientStops: [
        { offset: 0, color: '#041d30' },
        { offset: 0.5, color: '#083344' },
        { offset: 1, color: '#0e7490' }
      ],
      overlayColor: '#000000',
      overlayOpacity: 0.2,
      vignette: 50,
      grain: true,
      imageBrightness: 100,
      imageContrast: 100,
      imageSaturation: 100,
      imageBlur: 0
    },
    effects: {
      glassmorphism: true,
      frostedGlass: false,
      lightLeak: false,
      duotone: false,
      cinematicBorder: false,
      borderColor: '#38bdf8',
      borderWidth: 1
    },
    createLayers: (verseTa, verseEn, ref, w, h) => [
      {
        id: 'layer-verse-ta',
        name: 'Tamil Verse Text',
        type: 'text',
        role: 'verse-ta',
        text: verseTa || 'எல்லாப் புத்திக்கும் மேலான தேவ சமாதானம் உங்கள் இருதயங்களையும் உங்கள் சிந்தைகளையும் கிறிஸ்து இயேசுவுக்குள் காத்துக்கொள்ளும்.',
        fontFamily: `'Noto Serif Tamil', serif`,
        fontSize: Math.round(w * 0.044),
        fontWeight: '500',
        fontStyle: 'normal',
        textAlign: 'center',
        textColor: '#f0fdf4',
        lineHeight: 1.8,
        letterSpacing: 0.4,
        textTransform: 'none',
        shadowColor: 'rgba(0,0,0,0.85)',
        shadowBlur: 10,
        shadowOffsetX: 0,
        shadowOffsetY: 3,
        strokeColor: '',
        strokeWidth: 0,
        hasBgBox: false,
        bgBoxColor: '',
        bgBoxPadding: 0,
        bgBoxRadius: 0,
        x: w * 0.1,
        y: h * 0.28,
        width: w * 0.8,
        height: h * 0.38,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 1
      },
      {
        id: 'layer-ref',
        name: 'Bible Reference',
        type: 'text',
        role: 'reference',
        text: `— ${ref || 'பிலிப்பியர் 4:7'} —`,
        fontFamily: `'Cinzel', serif`,
        fontSize: Math.round(w * 0.03),
        fontWeight: '700',
        fontStyle: 'normal',
        textAlign: 'center',
        textColor: '#38bdf8',
        lineHeight: 1.3,
        letterSpacing: 2,
        textTransform: 'uppercase',
        shadowColor: 'rgba(56,189,248,0.5)',
        shadowBlur: 10,
        shadowOffsetX: 0,
        shadowOffsetY: 2,
        hasBgBox: false,
        bgBoxColor: '',
        bgBoxPadding: 0,
        bgBoxRadius: 0,
        strokeColor: '',
        strokeWidth: 0,
        x: w * 0.25,
        y: h * 0.74,
        width: w * 0.5,
        height: 42,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 2
      }
    ]
  },

  // 6. Forest Grace (Emerald / Sage Organic Nature)
  {
    id: 'forest-grace',
    name: 'Forest Grace',
    nameTa: 'பசுமை கிருபை',
    category: 'Nature',
    thumbnailGradient: 'linear-gradient(135deg, #064e3b, #047857)',
    canvasRatio: '1:1',
    background: {
      type: 'gradient',
      solidColor: '#03261d',
      gradientType: 'linear',
      gradientAngle: 135,
      gradientStops: [
        { offset: 0, color: '#022c22' },
        { offset: 0.55, color: '#064e3b' },
        { offset: 1, color: '#065f46' }
      ],
      overlayColor: '#000000',
      overlayOpacity: 0.25,
      vignette: 45,
      grain: true,
      imageBrightness: 100,
      imageContrast: 100,
      imageSaturation: 100,
      imageBlur: 0
    },
    effects: {
      glassmorphism: true,
      frostedGlass: false,
      lightLeak: false,
      duotone: false,
      cinematicBorder: false,
      borderColor: '#6ee7b7',
      borderWidth: 1
    },
    createLayers: (verseTa, verseEn, ref, w, h) => [
      {
        id: 'layer-verse-ta',
        name: 'Tamil Verse Text',
        type: 'text',
        role: 'verse-ta',
        text: verseTa || 'அவர் நீர்க்கால்களின் ஓரமாய் நடப்பட்டு, தன் காலத்தில் தன் கனியைத் தந்து... செய்கிறதெல்லாம் வாய்க்கும்.',
        fontFamily: `'Noto Serif Tamil', serif`,
        fontSize: Math.round(w * 0.046),
        fontWeight: '500',
        fontStyle: 'normal',
        textAlign: 'center',
        textColor: '#ecfdf5',
        lineHeight: 1.8,
        letterSpacing: 0.4,
        textTransform: 'none',
        shadowColor: 'rgba(0,0,0,0.85)',
        shadowBlur: 10,
        shadowOffsetX: 0,
        shadowOffsetY: 3,
        strokeColor: '',
        strokeWidth: 0,
        hasBgBox: false,
        bgBoxColor: '',
        bgBoxPadding: 0,
        bgBoxRadius: 0,
        x: w * 0.1,
        y: h * 0.28,
        width: w * 0.8,
        height: h * 0.38,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 1
      },
      {
        id: 'layer-ref',
        name: 'Bible Reference',
        type: 'text',
        role: 'reference',
        text: `— ${ref || 'சங்கீதம் 1:3'} —`,
        fontFamily: `'Cinzel', serif`,
        fontSize: Math.round(w * 0.03),
        fontWeight: '700',
        fontStyle: 'normal',
        textAlign: 'center',
        textColor: '#6ee7b7',
        lineHeight: 1.3,
        letterSpacing: 2,
        textTransform: 'uppercase',
        shadowColor: 'rgba(110,231,183,0.4)',
        shadowBlur: 8,
        shadowOffsetX: 0,
        shadowOffsetY: 2,
        hasBgBox: false,
        bgBoxColor: '',
        bgBoxPadding: 0,
        bgBoxRadius: 0,
        strokeColor: '',
        strokeWidth: 0,
        x: w * 0.25,
        y: h * 0.74,
        width: w * 0.5,
        height: 42,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 2
      }
    ]
  }
];

export const CANVAS_SIZES = CANVAS_PRESETS;
export const TAMIL_FONTS = TAMIL_FONTS_LIST.map(f => ({ family: f.name, name: f.name, nameTa: f.nameTa, category: 'Tamil' }));
export const ENGLISH_FONTS = ENGLISH_FONTS_LIST.map(f => ({ family: f.name, name: f.name, nameTa: f.nameTa, category: 'English' }));
