import { StudioTemplate, StudioLayer, TextLayer, ShapeLayer, ElementLayer } from './types';

export const CANVAS_PRESETS = [
  { id: '1:1' as const, name: 'Square Post', nameTa: '1:1 சதுரம்', sub: 'Instagram / WhatsApp DP', width: 1080, height: 1080, icon: '⬛' },
  { id: '9:16' as const, name: 'Story / Reel', nameTa: '9:16 ஸ்டோரி', sub: 'WhatsApp Status / Reels', width: 1080, height: 1920, icon: '📱' },
  { id: '4:5' as const, name: 'Feed Portrait', nameTa: '4:5 போர்ட்ரெய்ட்', sub: 'Instagram Portrait Feed', width: 1080, height: 1350, icon: '🖼' },
  { id: '16:9' as const, name: 'Landscape Banner', nameTa: '16:9 திரையகம்', sub: 'YouTube / Projection', width: 1920, height: 1080, icon: '🖥' },
];

export const TAMIL_FONTS_LIST = [
  { id: 'noto-serif', name: 'Noto Serif Tamil', nameTa: 'பாரம்பரியம் (Serif)', font: `'Noto Serif Tamil', Georgia, serif` },
  { id: 'noto-sans', name: 'Noto Sans Tamil', nameTa: 'நவீன எழுத்து (Sans)', font: `'Noto Sans Tamil', sans-serif` },
  { id: 'mukta', name: 'Mukta Malar', nameTa: 'அழகிய மலர்', font: `'Mukta Malar', 'Noto Sans Tamil', sans-serif` },
  { id: 'catamaran', name: 'Catamaran', nameTa: 'கம்பீர நடை', font: `'Catamaran', 'Noto Sans Tamil', sans-serif` },
  { id: 'kavivanar', name: 'Kavivanar Script', nameTa: 'கவிவாணர் எழுத்து', font: `'Kavivanar', cursive` },
  { id: 'baloo', name: 'Baloo Thambi', nameTa: 'தடிமன் பாலு (Rounded)', font: `'Baloo Thambi 2', sans-serif` },
  { id: 'hind', name: 'Hind Madurai', nameTa: 'மதுரை நடை', font: `'Hind Madurai', sans-serif` },
  { id: 'arima', name: 'Arima Script', nameTa: 'அரிமா கவிதை', font: `'Arima', cursive` },
];

export const ENGLISH_FONTS_LIST = [
  { id: 'cinzel', name: 'Cinzel Roman', nameTa: 'ராஜ கம்பீரம் (Cinzel)', font: `'Cinzel', Georgia, serif` },
  { id: 'playfair', name: 'Playfair Display', nameTa: 'அரண்மனை உரை (Playfair)', font: `'Playfair Display', Georgia, serif` },
  { id: 'lora', name: 'Lora Sacred', nameTa: 'வேதாகம உரை (Lora)', font: `'Lora', serif` },
  { id: 'inter', name: 'Inter Clean', nameTa: 'நவீன எழுத்து (Inter)', font: `'Inter', sans-serif` },
  { id: 'poppins', name: 'Poppins Bold', nameTa: 'நவீன வடிவம் (Poppins)', font: `'Poppins', sans-serif` },
  { id: 'caveat', name: 'Caveat Script', nameTa: 'கையொப்பம் (Caveat)', font: `'Caveat', cursive` },
];

export const STUDIO_TEMPLATES: StudioTemplate[] = [
  // 1. Golden Faith (Luxury Gold & Deep Dark)
  {
    id: 'golden-faith',
    name: 'Golden Faith',
    nameTa: 'தங்க விசுவாசம்',
    category: 'Luxury',
    thumbnailGradient: 'linear-gradient(135deg, #181206, #d97706)',
    canvasRatio: '1:1',
    background: {
      type: 'gradient',
      solidColor: '#120d04',
      gradientType: 'linear',
      gradientAngle: 145,
      gradientStops: [
        { offset: 0, color: '#0f0a02' },
        { offset: 0.55, color: '#1f1505' },
        { offset: 1, color: '#382506' }
      ],
      overlayColor: '#000000',
      overlayOpacity: 0.2,
      vignette: 45,
      grain: true,
      imageBrightness: 100,
      imageContrast: 100,
      imageSaturation: 100,
      imageBlur: 0
    },
    effects: {
      glassmorphism: true,
      frostedGlass: false,
      lightLeak: false,
      duotone: false,
      cinematicBorder: true,
      borderColor: '#fbbf24',
      borderWidth: 3
    },
    createLayers: (verseTa, verseEn, ref, w, h) => [
      {
        id: 'layer-frame',
        name: 'Gold Border Frame',
        type: 'shape',
        shapeType: 'rounded',
        x: w * 0.05,
        y: h * 0.05,
        width: w * 0.9,
        height: h * 0.9,
        rotation: 0,
        opacity: 0.7,
        visible: true,
        locked: true,
        zIndex: 1,
        fillColor: 'transparent',
        borderColor: '#fbbf24',
        borderWidth: 2,
        borderRadius: 24,
        shadowColor: '#d97706',
        shadowBlur: 14
      },
      {
        id: 'layer-symbol',
        name: 'Sacred Cross',
        type: 'element',
        elementId: 'cross-ornate',
        svgPath: 'M12 2v20M7 8h10',
        x: w * 0.5 - 20,
        y: h * 0.16,
        width: 40,
        height: 48,
        rotation: 0,
        opacity: 0.85,
        visible: true,
        locked: false,
        zIndex: 2,
        color: '#fbbf24',
        shadowColor: 'rgba(251,191,36,0.6)',
        shadowBlur: 12
      },
      {
        id: 'layer-verse-ta',
        name: 'Tamil Verse Text',
        type: 'text',
        role: 'verse-ta',
        text: verseTa || 'கர்த்தர் என் வெளிச்சமும் என் இரட்சிப்புமானவர், யாருக்குப் பயப்படுவேன்?',
        fontFamily: `'Noto Serif Tamil', Georgia, serif`,
        fontSize: Math.round(w * 0.046),
        fontWeight: '600',
        fontStyle: 'normal',
        textAlign: 'center',
        textColor: '#fef3c7',
        lineHeight: 1.7,
        letterSpacing: 0.5,
        textTransform: 'none',
        shadowColor: 'rgba(0,0,0,0.9)',
        shadowBlur: 10,
        shadowOffsetX: 0,
        shadowOffsetY: 3,
        strokeColor: '',
        strokeWidth: 0,
        hasBgBox: false,
        bgBoxColor: 'rgba(0,0,0,0.4)',
        bgBoxPadding: 16,
        bgBoxRadius: 16,
        x: w * 0.1,
        y: h * 0.32,
        width: w * 0.8,
        height: h * 0.35,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 3
      },
      {
        id: 'layer-verse-en',
        name: 'English Translation',
        type: 'text',
        role: 'verse-en',
        text: verseEn ? `"${verseEn}"` : '"The Lord is my light and my salvation; whom shall I fear?"',
        fontFamily: `'Lora', serif`,
        fontSize: Math.round(w * 0.026),
        fontWeight: '400',
        fontStyle: 'italic',
        textAlign: 'center',
        textColor: '#e2e8f0',
        lineHeight: 1.5,
        letterSpacing: 0.3,
        textTransform: 'none',
        shadowColor: 'rgba(0,0,0,0.8)',
        shadowBlur: 6,
        shadowOffsetX: 0,
        shadowOffsetY: 2,
        strokeColor: '',
        strokeWidth: 0,
        hasBgBox: false,
        bgBoxColor: '',
        bgBoxPadding: 0,
        bgBoxRadius: 0,
        x: w * 0.12,
        y: h * 0.67,
        width: w * 0.76,
        height: h * 0.14,
        rotation: 0,
        opacity: 0.9,
        visible: !!verseEn,
        locked: false,
        zIndex: 4
      },
      {
        id: 'layer-ref',
        name: 'Scripture Reference',
        type: 'text',
        role: 'reference',
        text: `— ${ref || 'சங்கீதம் 27:1'} —`,
        fontFamily: `'Cinzel', 'Noto Serif Tamil', serif`,
        fontSize: Math.round(w * 0.032),
        fontWeight: '700',
        fontStyle: 'normal',
        textAlign: 'center',
        textColor: '#fbbf24',
        lineHeight: 1.3,
        letterSpacing: 2,
        textTransform: 'uppercase',
        shadowColor: 'rgba(217,119,6,0.6)',
        shadowBlur: 8,
        shadowOffsetX: 0,
        shadowOffsetY: 2,
        hasBgBox: true,
        bgBoxColor: 'rgba(251,191,36,0.12)',
        bgBoxPadding: 8,
        bgBoxRadius: 99,
        strokeColor: '',
        strokeWidth: 0,
        x: w * 0.25,
        y: h * 0.83,
        width: w * 0.5,
        height: 48,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 5
      }
    ]
  },

  // 2. Cinematic Worship (Deep Indigo & Purple Glow)
  {
    id: 'cinematic-worship',
    name: 'Cinematic Worship',
    nameTa: 'ஆராதனை ஒளி',
    category: 'Cinematic',
    thumbnailGradient: 'linear-gradient(135deg, #090919, #6d28d9)',
    canvasRatio: '9:16',
    background: {
      type: 'gradient',
      solidColor: '#070614',
      gradientType: 'linear',
      gradientAngle: 180,
      gradientStops: [
        { offset: 0, color: '#090518' },
        { offset: 0.45, color: '#170c36' },
        { offset: 1, color: '#04020a' }
      ],
      overlayColor: '#7c3aed',
      overlayOpacity: 0.15,
      vignette: 55,
      grain: true,
      imageBrightness: 100,
      imageContrast: 100,
      imageSaturation: 100,
      imageBlur: 0
    },
    effects: {
      glassmorphism: true,
      frostedGlass: true,
      lightLeak: true,
      duotone: false,
      cinematicBorder: false,
      borderColor: '#a78bfa',
      borderWidth: 1
    },
    createLayers: (verseTa, verseEn, ref, w, h) => [
      {
        id: 'layer-glass-card',
        name: 'Frosted Glass Backdrop',
        type: 'shape',
        shapeType: 'rounded',
        x: w * 0.08,
        y: h * 0.26,
        width: w * 0.84,
        height: h * 0.52,
        rotation: 0,
        opacity: 0.88,
        visible: true,
        locked: true,
        zIndex: 1,
        fillColor: 'rgba(255,255,255,0.06)',
        borderColor: 'rgba(255,255,255,0.18)',
        borderWidth: 1.5,
        borderRadius: 28,
        shadowColor: 'rgba(0,0,0,0.6)',
        shadowBlur: 24
      },
      {
        id: 'layer-verse-ta',
        name: 'Tamil Verse Text',
        type: 'text',
        role: 'verse-ta',
        text: verseTa || 'நான் உன்னை விட்டு விலகுவதுமில்லை, உன்னைக் கைவிடுவதுமில்லை.',
        fontFamily: `'Noto Serif Tamil', serif`,
        fontSize: Math.round(w * 0.052),
        fontWeight: '600',
        fontStyle: 'normal',
        textAlign: 'center',
        textColor: '#f8fafc',
        lineHeight: 1.8,
        letterSpacing: 0.5,
        textTransform: 'none',
        shadowColor: 'rgba(0,0,0,0.9)',
        shadowBlur: 14,
        shadowOffsetX: 0,
        shadowOffsetY: 4,
        strokeColor: '',
        strokeWidth: 0,
        hasBgBox: false,
        bgBoxColor: '',
        bgBoxPadding: 0,
        bgBoxRadius: 0,
        x: w * 0.12,
        y: h * 0.33,
        width: w * 0.76,
        height: h * 0.26,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 2
      },
      {
        id: 'layer-verse-en',
        name: 'English Translation',
        type: 'text',
        role: 'verse-en',
        text: verseEn ? `"${verseEn}"` : '"I will never leave you nor forsake you."',
        fontFamily: `'Lora', serif`,
        fontSize: Math.round(w * 0.034),
        fontWeight: '400',
        fontStyle: 'italic',
        textAlign: 'center',
        textColor: '#c4b5fd',
        lineHeight: 1.6,
        letterSpacing: 0.5,
        textTransform: 'none',
        shadowColor: 'rgba(0,0,0,0.7)',
        shadowBlur: 8,
        shadowOffsetX: 0,
        shadowOffsetY: 2,
        hasBgBox: false,
        bgBoxColor: '',
        bgBoxPadding: 0,
        bgBoxRadius: 0,
        strokeColor: '',
        strokeWidth: 0,
        x: w * 0.12,
        y: h * 0.60,
        width: w * 0.76,
        height: h * 0.12,
        rotation: 0,
        opacity: 0.95,
        visible: true,
        locked: false,
        zIndex: 3
      },
      {
        id: 'layer-ref',
        name: 'Bible Reference',
        type: 'text',
        role: 'reference',
        text: `[ ${ref || 'யோசுவா 1:5'} ]`,
        fontFamily: `'Cinzel', sans-serif`,
        fontSize: Math.round(w * 0.036),
        fontWeight: '700',
        fontStyle: 'normal',
        textAlign: 'center',
        textColor: '#a78bfa',
        lineHeight: 1.4,
        letterSpacing: 2.5,
        textTransform: 'uppercase',
        shadowColor: 'rgba(124,58,237,0.5)',
        shadowBlur: 10,
        shadowOffsetX: 0,
        shadowOffsetY: 2,
        hasBgBox: false,
        bgBoxColor: '',
        bgBoxPadding: 0,
        bgBoxRadius: 0,
        strokeColor: '',
        strokeWidth: 0,
        x: w * 0.2,
        y: h * 0.73,
        width: w * 0.6,
        height: 50,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 4
      }
    ]
  },

  // 3. Minimal White (Pristine Editorial Typography)
  {
    id: 'minimal-white',
    name: 'Minimal White',
    nameTa: 'தூய வெண்மை',
    category: 'Minimal',
    thumbnailGradient: 'linear-gradient(135deg, #f8fafc, #e2e8f0)',
    canvasRatio: '1:1',
    background: {
      type: 'solid',
      solidColor: '#ffffff',
      gradientType: 'linear',
      gradientAngle: 0,
      gradientStops: [],
      overlayColor: '#000000',
      overlayOpacity: 0,
      vignette: 0,
      grain: false,
      imageBrightness: 100,
      imageContrast: 100,
      imageSaturation: 100,
      imageBlur: 0
    },
    effects: {
      glassmorphism: false,
      frostedGlass: false,
      lightLeak: false,
      duotone: false,
      cinematicBorder: false,
      borderColor: '#e2e8f0',
      borderWidth: 1
    },
    createLayers: (verseTa, verseEn, ref, w, h) => [
      {
        id: 'layer-accent-bar',
        name: 'Top Accent Line',
        type: 'shape',
        shapeType: 'rect',
        x: w * 0.44,
        y: h * 0.18,
        width: w * 0.12,
        height: 4,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: true,
        zIndex: 1,
        fillColor: '#0f172a',
        borderColor: 'transparent',
        borderWidth: 0,
        borderRadius: 99,
        shadowColor: 'transparent',
        shadowBlur: 0
      },
      {
        id: 'layer-verse-ta',
        name: 'Tamil Verse Text',
        type: 'text',
        role: 'verse-ta',
        text: verseTa || 'தேவன் நமக்கு அடைக்கலமும் பெலனும், ஆபத்துக்காலத்தில் அனுகூலமான துணையுமானவர்.',
        fontFamily: `'Noto Serif Tamil', Georgia, serif`,
        fontSize: Math.round(w * 0.046),
        fontWeight: '500',
        fontStyle: 'normal',
        textAlign: 'center',
        textColor: '#0f172a',
        lineHeight: 1.85,
        letterSpacing: 0.3,
        textTransform: 'none',
        shadowColor: 'transparent',
        shadowBlur: 0,
        shadowOffsetX: 0,
        shadowOffsetY: 0,
        strokeColor: '',
        strokeWidth: 0,
        hasBgBox: false,
        bgBoxColor: '',
        bgBoxPadding: 0,
        bgBoxRadius: 0,
        x: w * 0.12,
        y: h * 0.28,
        width: w * 0.76,
        height: h * 0.36,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 2
      },
      {
        id: 'layer-verse-en',
        name: 'English Translation',
        type: 'text',
        role: 'verse-en',
        text: verseEn ? `"${verseEn}"` : '"God is our refuge and strength, an ever-present help in trouble."',
        fontFamily: `'Lora', serif`,
        fontSize: Math.round(w * 0.026),
        fontWeight: '400',
        fontStyle: 'normal',
        textAlign: 'center',
        textColor: '#475569',
        lineHeight: 1.6,
        letterSpacing: 0.3,
        textTransform: 'none',
        shadowColor: 'transparent',
        shadowBlur: 0,
        shadowOffsetX: 0,
        shadowOffsetY: 0,
        hasBgBox: false,
        bgBoxColor: '',
        bgBoxPadding: 0,
        bgBoxRadius: 0,
        strokeColor: '',
        strokeWidth: 0,
        x: w * 0.14,
        y: h * 0.66,
        width: w * 0.72,
        height: h * 0.12,
        rotation: 0,
        opacity: 0.9,
        visible: true,
        locked: false,
        zIndex: 3
      },
      {
        id: 'layer-ref',
        name: 'Bible Reference',
        type: 'text',
        role: 'reference',
        text: `— ${ref || 'சங்கீதம் 46:1'} —`,
        fontFamily: `'Playfair Display', serif`,
        fontSize: Math.round(w * 0.028),
        fontWeight: '700',
        fontStyle: 'normal',
        textAlign: 'center',
        textColor: '#0f172a',
        lineHeight: 1.4,
        letterSpacing: 2,
        textTransform: 'uppercase',
        shadowColor: 'transparent',
        shadowBlur: 0,
        shadowOffsetX: 0,
        shadowOffsetY: 0,
        hasBgBox: false,
        bgBoxColor: '',
        bgBoxPadding: 0,
        bgBoxRadius: 0,
        strokeColor: '',
        strokeWidth: 0,
        x: w * 0.25,
        y: h * 0.81,
        width: w * 0.5,
        height: 40,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 4
      }
    ]
  },

  // 4. Sunset Prayer (Warm Amber Gradient)
  {
    id: 'sunset-prayer',
    name: 'Sunset Prayer',
    nameTa: 'அந்தி ஜெபம்',
    category: 'Warm',
    thumbnailGradient: 'linear-gradient(135deg, #b45309, #dc2626)',
    canvasRatio: '4:5',
    background: {
      type: 'gradient',
      solidColor: '#1c0e06',
      gradientType: 'linear',
      gradientAngle: 150,
      gradientStops: [
        { offset: 0, color: '#f59e0b' },
        { offset: 0.45, color: '#ea580c' },
        { offset: 1, color: '#b91c1c' }
      ],
      overlayColor: '#000000',
      overlayOpacity: 0.35,
      vignette: 40,
      grain: true,
      imageBrightness: 100,
      imageContrast: 100,
      imageSaturation: 100,
      imageBlur: 0
    },
    effects: {
      glassmorphism: true,
      frostedGlass: false,
      lightLeak: false,
      duotone: false,
      cinematicBorder: true,
      borderColor: '#fef08a',
      borderWidth: 1.5
    },
    createLayers: (verseTa, verseEn, ref, w, h) => [
      {
        id: 'layer-verse-ta',
        name: 'Tamil Verse Text',
        type: 'text',
        role: 'verse-ta',
        text: verseTa || 'அவர் காலையில்தோறும் புதியவைகள்; உமது உண்மை பெரிதாயிருக்கிறது.',
        fontFamily: `'Noto Serif Tamil', serif`,
        fontSize: Math.round(w * 0.048),
        fontWeight: '600',
        fontStyle: 'normal',
        textAlign: 'center',
        textColor: '#ffffff',
        lineHeight: 1.75,
        letterSpacing: 0.5,
        textTransform: 'none',
        shadowColor: 'rgba(0,0,0,0.9)',
        shadowBlur: 14,
        shadowOffsetX: 0,
        shadowOffsetY: 3,
        strokeColor: '',
        strokeWidth: 0,
        hasBgBox: false,
        bgBoxColor: '',
        bgBoxPadding: 0,
        bgBoxRadius: 0,
        x: w * 0.1,
        y: h * 0.30,
        width: w * 0.8,
        height: h * 0.32,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 1
      },
      {
        id: 'layer-ref',
        name: 'Bible Reference',
        type: 'text',
        role: 'reference',
        text: `• ${ref || 'புலம்பல் 3:23'} •`,
        fontFamily: `'Cinzel', serif`,
        fontSize: Math.round(w * 0.032),
        fontWeight: '700',
        fontStyle: 'normal',
        textAlign: 'center',
        textColor: '#fef08a',
        lineHeight: 1.3,
        letterSpacing: 2,
        textTransform: 'uppercase',
        shadowColor: 'rgba(0,0,0,0.8)',
        shadowBlur: 8,
        shadowOffsetX: 0,
        shadowOffsetY: 2,
        hasBgBox: true,
        bgBoxColor: 'rgba(0,0,0,0.3)',
        bgBoxPadding: 10,
        bgBoxRadius: 99,
        strokeColor: '',
        strokeWidth: 0,
        x: w * 0.25,
        y: h * 0.72,
        width: w * 0.5,
        height: 48,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 2
      }
    ]
  },

  // 5. Ocean Peace (Serene Navy Teal Deep Waters)
  {
    id: 'ocean-peace',
    name: 'Ocean Peace',
    nameTa: 'ஆழி சமாதானம்',
    category: 'Serene',
    thumbnailGradient: 'linear-gradient(135deg, #082f49, #0284c7)',
    canvasRatio: '1:1',
    background: {
      type: 'gradient',
      solidColor: '#031a29',
      gradientType: 'linear',
      gradientAngle: 160,
      gradientStops: [
        { offset: 0, color: '#041d30' },
        { offset: 0.5, color: '#083344' },
        { offset: 1, color: '#0e7490' }
      ],
      overlayColor: '#000000',
      overlayOpacity: 0.2,
      vignette: 50,
      grain: true,
      imageBrightness: 100,
      imageContrast: 100,
      imageSaturation: 100,
      imageBlur: 0
    },
    effects: {
      glassmorphism: true,
      frostedGlass: false,
      lightLeak: false,
      duotone: false,
      cinematicBorder: false,
      borderColor: '#38bdf8',
      borderWidth: 1
    },
    createLayers: (verseTa, verseEn, ref, w, h) => [
      {
        id: 'layer-verse-ta',
        name: 'Tamil Verse Text',
        type: 'text',
        role: 'verse-ta',
        text: verseTa || 'எல்லாப் புத்திக்கும் மேலான தேவ சமாதானம் உங்கள் இருதயங்களையும் உங்கள் சிந்தைகளையும் கிறிஸ்து இயேசுவுக்குள் காத்துக்கொள்ளும்.',
        fontFamily: `'Noto Serif Tamil', serif`,
        fontSize: Math.round(w * 0.044),
        fontWeight: '500',
        fontStyle: 'normal',
        textAlign: 'center',
        textColor: '#f0fdf4',
        lineHeight: 1.8,
        letterSpacing: 0.4,
        textTransform: 'none',
        shadowColor: 'rgba(0,0,0,0.85)',
        shadowBlur: 10,
        shadowOffsetX: 0,
        shadowOffsetY: 3,
        strokeColor: '',
        strokeWidth: 0,
        hasBgBox: false,
        bgBoxColor: '',
        bgBoxPadding: 0,
        bgBoxRadius: 0,
        x: w * 0.1,
        y: h * 0.28,
        width: w * 0.8,
        height: h * 0.38,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 1
      },
      {
        id: 'layer-ref',
        name: 'Bible Reference',
        type: 'text',
        role: 'reference',
        text: `— ${ref || 'பிலிப்பியர் 4:7'} —`,
        fontFamily: `'Cinzel', serif`,
        fontSize: Math.round(w * 0.03),
        fontWeight: '700',
        fontStyle: 'normal',
        textAlign: 'center',
        textColor: '#38bdf8',
        lineHeight: 1.3,
        letterSpacing: 2,
        textTransform: 'uppercase',
        shadowColor: 'rgba(56,189,248,0.5)',
        shadowBlur: 10,
        shadowOffsetX: 0,
        shadowOffsetY: 2,
        hasBgBox: false,
        bgBoxColor: '',
        bgBoxPadding: 0,
        bgBoxRadius: 0,
        strokeColor: '',
        strokeWidth: 0,
        x: w * 0.25,
        y: h * 0.74,
        width: w * 0.5,
        height: 42,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 2
      }
    ]
  },

  // 6. Forest Grace (Emerald / Sage Organic Nature)
  {
    id: 'forest-grace',
    name: 'Forest Grace',
    nameTa: 'பசுமை கிருபை',
    category: 'Nature',
    thumbnailGradient: 'linear-gradient(135deg, #064e3b, #047857)',
    canvasRatio: '1:1',
    background: {
      type: 'gradient',
      solidColor: '#03261d',
      gradientType: 'linear',
      gradientAngle: 135,
      gradientStops: [
        { offset: 0, color: '#022c22' },
        { offset: 0.55, color: '#064e3b' },
        { offset: 1, color: '#065f46' }
      ],
      overlayColor: '#000000',
      overlayOpacity: 0.25,
      vignette: 45,
      grain: true,
      imageBrightness: 100,
      imageContrast: 100,
      imageSaturation: 100,
      imageBlur: 0
    },
    effects: {
      glassmorphism: true,
      frostedGlass: false,
      lightLeak: false,
      duotone: false,
      cinematicBorder: false,
      borderColor: '#6ee7b7',
      borderWidth: 1
    },
    createLayers: (verseTa, verseEn, ref, w, h) => [
      {
        id: 'layer-verse-ta',
        name: 'Tamil Verse Text',
        type: 'text',
        role: 'verse-ta',
        text: verseTa || 'அவர் நீர்க்கால்களின் ஓரமாய் நடப்பட்டு, தன் காலத்தில் தன் கனியைத் தந்து... செய்கிறதெல்லாம் வாய்க்கும்.',
        fontFamily: `'Noto Serif Tamil', serif`,
        fontSize: Math.round(w * 0.046),
        fontWeight: '500',
        fontStyle: 'normal',
        textAlign: 'center',
        textColor: '#ecfdf5',
        lineHeight: 1.8,
        letterSpacing: 0.4,
        textTransform: 'none',
        shadowColor: 'rgba(0,0,0,0.85)',
        shadowBlur: 10,
        shadowOffsetX: 0,
        shadowOffsetY: 3,
        strokeColor: '',
        strokeWidth: 0,
        hasBgBox: false,
        bgBoxColor: '',
        bgBoxPadding: 0,
        bgBoxRadius: 0,
        x: w * 0.1,
        y: h * 0.28,
        width: w * 0.8,
        height: h * 0.38,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 1
      },
      {
        id: 'layer-ref',
        name: 'Bible Reference',
        type: 'text',
        role: 'reference',
        text: `— ${ref || 'சங்கீதம் 1:3'} —`,
        fontFamily: `'Cinzel', serif`,
        fontSize: Math.round(w * 0.03),
        fontWeight: '700',
        fontStyle: 'normal',
        textAlign: 'center',
        textColor: '#6ee7b7',
        lineHeight: 1.3,
        letterSpacing: 2,
        textTransform: 'uppercase',
        shadowColor: 'rgba(110,231,183,0.4)',
        shadowBlur: 8,
        shadowOffsetX: 0,
        shadowOffsetY: 2,
        hasBgBox: false,
        bgBoxColor: '',
        bgBoxPadding: 0,
        bgBoxRadius: 0,
        strokeColor: '',
        strokeWidth: 0,
        x: w * 0.25,
        y: h * 0.74,
        width: w * 0.5,
        height: 42,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 2
      }
    ]
  },

  // 7. Heavenly Dawn (Warm Celestial Rose Sunrise)
  {
    id: 'heavenly-dawn',
    name: 'Heavenly Dawn',
    nameTa: 'விடியலின் கிருபை',
    category: 'Warm',
    thumbnailGradient: 'linear-gradient(135deg, #2d0b1e, #be185d, #f59e0b)',
    canvasRatio: '1:1',
    background: {
      type: 'gradient',
      solidColor: '#1e0817',
      gradientType: 'linear',
      gradientAngle: 155,
      gradientStops: [
        { offset: 0, color: '#160511' },
        { offset: 0.5, color: '#3b0d26' },
        { offset: 1, color: '#701a40' }
      ],
      overlayColor: '#000000',
      overlayOpacity: 0.15,
      vignette: 35,
      grain: true,
      imageBrightness: 100,
      imageContrast: 100,
      imageSaturation: 100,
      imageBlur: 0
    },
    effects: {
      glassmorphism: true,
      frostedGlass: true,
      lightLeak: true,
      duotone: false,
      cinematicBorder: false,
      borderColor: '#f43f5e',
      borderWidth: 1
    },
    createLayers: (verseTa, verseEn, ref, w, h) => [
      {
        id: 'layer-sun-glow',
        name: 'Celestial Aura',
        type: 'shape',
        shapeType: 'circle',
        x: w * 0.5 - w * 0.22,
        y: h * 0.1,
        width: w * 0.44,
        height: w * 0.44,
        rotation: 0,
        opacity: 0.35,
        visible: true,
        locked: true,
        zIndex: 1,
        fillColor: 'rgba(244, 63, 94, 0.25)',
        borderColor: 'rgba(251, 191, 36, 0.4)',
        borderWidth: 1,
        borderRadius: 999,
        shadowColor: 'rgba(244, 63, 94, 0.6)',
        shadowBlur: 30
      },
      {
        id: 'layer-cross',
        name: 'Dawn Cross',
        type: 'element',
        elementId: 'cross-latin',
        svgPath: 'M12 2v20M7 8h10',
        x: w * 0.5 - 18,
        y: h * 0.16,
        width: 36,
        height: 44,
        rotation: 0,
        opacity: 0.9,
        visible: true,
        locked: false,
        zIndex: 2,
        color: '#fef08a',
        shadowColor: 'rgba(245, 158, 11, 0.7)',
        shadowBlur: 14
      },
      {
        id: 'layer-verse-ta',
        name: 'Tamil Verse Text',
        type: 'text',
        role: 'verse-ta',
        text: verseTa || 'காலைதோறும் இவைகள் புதியது; உமது உண்மை பெரிதாயிருக்கிறது.',
        fontFamily: `'Noto Serif Tamil', Georgia, serif`,
        fontSize: Math.round(w * 0.048),
        fontWeight: '600',
        fontStyle: 'normal',
        textAlign: 'center',
        textColor: '#fff1f2',
        lineHeight: 1.75,
        letterSpacing: 0.5,
        textTransform: 'none',
        shadowColor: 'rgba(0,0,0,0.85)',
        shadowBlur: 12,
        shadowOffsetX: 0,
        shadowOffsetY: 3,
        hasBgBox: false,
        bgBoxColor: '',
        bgBoxPadding: 0,
        bgBoxRadius: 0,
        strokeColor: '',
        strokeWidth: 0,
        x: w * 0.1,
        y: h * 0.33,
        width: w * 0.8,
        height: h * 0.32,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 3
      },
      {
        id: 'layer-verse-en',
        name: 'English Translation',
        type: 'text',
        role: 'verse-en',
        text: verseEn ? `"${verseEn}"` : '"They are new every morning; great is your faithfulness."',
        fontFamily: `'Lora', serif`,
        fontSize: Math.round(w * 0.027),
        fontWeight: '400',
        fontStyle: 'italic',
        textAlign: 'center',
        textColor: '#fecdd3',
        lineHeight: 1.5,
        letterSpacing: 0.4,
        textTransform: 'none',
        shadowColor: 'rgba(0,0,0,0.7)',
        shadowBlur: 6,
        shadowOffsetX: 0,
        shadowOffsetY: 1,
        hasBgBox: false,
        bgBoxColor: '',
        bgBoxPadding: 0,
        bgBoxRadius: 0,
        strokeColor: '',
        strokeWidth: 0,
        x: w * 0.12,
        y: h * 0.67,
        width: w * 0.76,
        height: h * 0.12,
        rotation: 0,
        opacity: 0.95,
        visible: !!verseEn,
        locked: false,
        zIndex: 4
      },
      {
        id: 'layer-ref',
        name: 'Scripture Reference',
        type: 'text',
        role: 'reference',
        text: `— ${ref || 'புலம்பல் 3:23'} —`,
        fontFamily: `'Cinzel', 'Noto Serif Tamil', serif`,
        fontSize: Math.round(w * 0.032),
        fontWeight: '700',
        fontStyle: 'normal',
        textAlign: 'center',
        textColor: '#fbbf24',
        lineHeight: 1.3,
        letterSpacing: 2,
        textTransform: 'uppercase',
        shadowColor: 'rgba(244,63,94,0.6)',
        shadowBlur: 8,
        shadowOffsetX: 0,
        shadowOffsetY: 2,
        hasBgBox: true,
        bgBoxColor: 'rgba(244, 63, 94, 0.25)',
        bgBoxPadding: 8,
        bgBoxRadius: 99,
        strokeColor: '',
        strokeWidth: 0,
        x: w * 0.25,
        y: h * 0.82,
        width: w * 0.5,
        height: 44,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 5
      }
    ]
  },

  // 8. Midnight Lamp (Deep Obsidian with Radiance)
  {
    id: 'midnight-lamp',
    name: 'Midnight Lamp',
    nameTa: 'இரவின் தீபம்',
    category: 'Cinematic',
    thumbnailGradient: 'linear-gradient(135deg, #09090b, #451a03, #d97706)',
    canvasRatio: '1:1',
    background: {
      type: 'gradient',
      solidColor: '#09090b',
      gradientType: 'linear',
      gradientAngle: 180,
      gradientStops: [
        { offset: 0, color: '#09090b' },
        { offset: 0.6, color: '#1c1005' },
        { offset: 1, color: '#381c03' }
      ],
      overlayColor: '#000000',
      overlayOpacity: 0.1,
      vignette: 50,
      grain: true,
      imageBrightness: 100,
      imageContrast: 100,
      imageSaturation: 100,
      imageBlur: 0
    },
    effects: {
      glassmorphism: true,
      frostedGlass: false,
      lightLeak: true,
      duotone: false,
      cinematicBorder: true,
      borderColor: '#d97706',
      borderWidth: 2
    },
    createLayers: (verseTa, verseEn, ref, w, h) => [
      {
        id: 'layer-frame',
        name: 'Amber Border Frame',
        type: 'shape',
        shapeType: 'rounded',
        x: w * 0.06,
        y: h * 0.06,
        width: w * 0.88,
        height: h * 0.88,
        rotation: 0,
        opacity: 0.8,
        visible: true,
        locked: true,
        zIndex: 1,
        fillColor: 'transparent',
        borderColor: '#d97706',
        borderWidth: 1.5,
        borderRadius: 20,
        shadowColor: '#b45309',
        shadowBlur: 16
      },
      {
        id: 'layer-verse-ta',
        name: 'Tamil Verse Text',
        type: 'text',
        role: 'verse-ta',
        text: verseTa || 'உம்முடைய வசனம் என் கால்களுக்குத் தீபமும், என் பாதைக்கு வெளிச்சமுமாயிருக்கிறது.',
        fontFamily: `'Noto Serif Tamil', Georgia, serif`,
        fontSize: Math.round(w * 0.048),
        fontWeight: '600',
        fontStyle: 'normal',
        textAlign: 'center',
        textColor: '#fef08a',
        lineHeight: 1.7,
        letterSpacing: 0.5,
        textTransform: 'none',
        shadowColor: 'rgba(0,0,0,0.95)',
        shadowBlur: 14,
        shadowOffsetX: 0,
        shadowOffsetY: 3,
        hasBgBox: false,
        bgBoxColor: '',
        bgBoxPadding: 0,
        bgBoxRadius: 0,
        strokeColor: '',
        strokeWidth: 0,
        x: w * 0.1,
        y: h * 0.3,
        width: w * 0.8,
        height: h * 0.35,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 2
      },
      {
        id: 'layer-verse-en',
        name: 'English Translation',
        type: 'text',
        role: 'verse-en',
        text: verseEn ? `"${verseEn}"` : '"Your word is a lamp to my feet and a light to my path."',
        fontFamily: `'Playfair Display', serif`,
        fontSize: Math.round(w * 0.028),
        fontWeight: '400',
        fontStyle: 'italic',
        textAlign: 'center',
        textColor: '#fed7aa',
        lineHeight: 1.5,
        letterSpacing: 0.4,
        textTransform: 'none',
        shadowColor: 'rgba(0,0,0,0.85)',
        shadowBlur: 8,
        shadowOffsetX: 0,
        shadowOffsetY: 1,
        hasBgBox: false,
        bgBoxColor: '',
        bgBoxPadding: 0,
        bgBoxRadius: 0,
        strokeColor: '',
        strokeWidth: 0,
        x: w * 0.12,
        y: h * 0.65,
        width: w * 0.76,
        height: h * 0.12,
        rotation: 0,
        opacity: 0.95,
        visible: !!verseEn,
        locked: false,
        zIndex: 3
      },
      {
        id: 'layer-ref',
        name: 'Bible Reference',
        type: 'text',
        role: 'reference',
        text: `— ${ref || 'சங்கீதம் 119:105'} —`,
        fontFamily: `'Cinzel', serif`,
        fontSize: Math.round(w * 0.032),
        fontWeight: '700',
        fontStyle: 'normal',
        textAlign: 'center',
        textColor: '#fbbf24',
        lineHeight: 1.3,
        letterSpacing: 2,
        textTransform: 'uppercase',
        shadowColor: 'rgba(217,119,6,0.6)',
        shadowBlur: 8,
        shadowOffsetX: 0,
        shadowOffsetY: 2,
        hasBgBox: true,
        bgBoxColor: 'rgba(217, 119, 6, 0.18)',
        bgBoxPadding: 8,
        bgBoxRadius: 99,
        strokeColor: '',
        strokeWidth: 0,
        x: w * 0.25,
        y: h * 0.8,
        width: w * 0.5,
        height: 44,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 4
      }
    ]
  },

  // 9. Living Water (Serene Turquoise & Cyan Waters)
  {
    id: 'living-water',
    name: 'Living Water',
    nameTa: 'ஜீவத்தண்ணீர்',
    category: 'Serene',
    thumbnailGradient: 'linear-gradient(135deg, #022221, #0d9488, #38bdf8)',
    canvasRatio: '1:1',
    background: {
      type: 'gradient',
      solidColor: '#022221',
      gradientType: 'linear',
      gradientAngle: 145,
      gradientStops: [
        { offset: 0, color: '#011c1b' },
        { offset: 0.55, color: '#09433e' },
        { offset: 1, color: '#0e7490' }
      ],
      overlayColor: '#000000',
      overlayOpacity: 0.15,
      vignette: 40,
      grain: false,
      imageBrightness: 100,
      imageContrast: 100,
      imageSaturation: 100,
      imageBlur: 0
    },
    effects: {
      glassmorphism: true,
      frostedGlass: true,
      lightLeak: false,
      duotone: false,
      cinematicBorder: false,
      borderColor: '#2dd4bf',
      borderWidth: 1.5
    },
    createLayers: (verseTa, verseEn, ref, w, h) => [
      {
        id: 'layer-glass-plate',
        name: 'Aquatic Frosted Backplate',
        type: 'shape',
        shapeType: 'rounded',
        x: w * 0.08,
        y: h * 0.25,
        width: w * 0.84,
        height: h * 0.54,
        rotation: 0,
        opacity: 0.9,
        visible: true,
        locked: true,
        zIndex: 1,
        fillColor: 'rgba(255, 255, 255, 0.05)',
        borderColor: 'rgba(45, 212, 191, 0.25)',
        borderWidth: 1.5,
        borderRadius: 24,
        shadowColor: 'rgba(0,0,0,0.6)',
        shadowBlur: 20
      },
      {
        id: 'layer-verse-ta',
        name: 'Tamil Verse Text',
        type: 'text',
        role: 'verse-ta',
        text: verseTa || 'தாகமாயிருக்கிறவன் என்னிடத்தில் வந்து பானம்பண்ணக்கடவன்; ஜீவத்தண்ணீருள்ள நதிகள் அவன் உள்ளத்திலிருந்து ஓடும்.',
        fontFamily: `'Mukta Malar', 'Noto Serif Tamil', sans-serif`,
        fontSize: Math.round(w * 0.046),
        fontWeight: '600',
        fontStyle: 'normal',
        textAlign: 'center',
        textColor: '#f0fdfa',
        lineHeight: 1.75,
        letterSpacing: 0.4,
        textTransform: 'none',
        shadowColor: 'rgba(0,0,0,0.85)',
        shadowBlur: 12,
        shadowOffsetX: 0,
        shadowOffsetY: 3,
        hasBgBox: false,
        bgBoxColor: '',
        bgBoxPadding: 0,
        bgBoxRadius: 0,
        strokeColor: '',
        strokeWidth: 0,
        x: w * 0.12,
        y: h * 0.32,
        width: w * 0.76,
        height: h * 0.28,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 2
      },
      {
        id: 'layer-verse-en',
        name: 'English Translation',
        type: 'text',
        role: 'verse-en',
        text: verseEn ? `"${verseEn}"` : '"Whoever is thirsty, let him come to me and drink. Rivers of living water will flow from within them."',
        fontFamily: `'Inter', sans-serif`,
        fontSize: Math.round(w * 0.026),
        fontWeight: '400',
        fontStyle: 'normal',
        textAlign: 'center',
        textColor: '#a5f3fc',
        lineHeight: 1.5,
        letterSpacing: 0.3,
        textTransform: 'none',
        shadowColor: 'rgba(0,0,0,0.7)',
        shadowBlur: 6,
        shadowOffsetX: 0,
        shadowOffsetY: 1,
        hasBgBox: false,
        bgBoxColor: '',
        bgBoxPadding: 0,
        bgBoxRadius: 0,
        strokeColor: '',
        strokeWidth: 0,
        x: w * 0.12,
        y: h * 0.62,
        width: w * 0.76,
        height: h * 0.12,
        rotation: 0,
        opacity: 0.95,
        visible: !!verseEn,
        locked: false,
        zIndex: 3
      },
      {
        id: 'layer-ref',
        name: 'Scripture Reference',
        type: 'text',
        role: 'reference',
        text: `[ ${ref || 'யோவான் 7:38'} ]`,
        fontFamily: `'Cinzel', serif`,
        fontSize: Math.round(w * 0.032),
        fontWeight: '700',
        fontStyle: 'normal',
        textAlign: 'center',
        textColor: '#38bdf8',
        lineHeight: 1.3,
        letterSpacing: 2,
        textTransform: 'uppercase',
        shadowColor: 'rgba(56,189,248,0.5)',
        shadowBlur: 8,
        shadowOffsetX: 0,
        shadowOffsetY: 2,
        hasBgBox: false,
        bgBoxColor: '',
        bgBoxPadding: 0,
        bgBoxRadius: 0,
        strokeColor: '',
        strokeWidth: 0,
        x: w * 0.25,
        y: h * 0.74,
        width: w * 0.5,
        height: 42,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 4
      }
    ]
  },

  // 10. Ancient Parchment (Historical Sacred Script)
  {
    id: 'ancient-scroll',
    name: 'Ancient Parchment',
    nameTa: 'பழங்கால வேத சுருள்',
    category: 'Luxury',
    thumbnailGradient: 'linear-gradient(135deg, #1f160e, #78350f, #d97706)',
    canvasRatio: '1:1',
    background: {
      type: 'gradient',
      solidColor: '#1c130b',
      gradientType: 'linear',
      gradientAngle: 135,
      gradientStops: [
        { offset: 0, color: '#170f08' },
        { offset: 0.6, color: '#291b10' },
        { offset: 1, color: '#3d2817' }
      ],
      overlayColor: '#000000',
      overlayOpacity: 0.2,
      vignette: 45,
      grain: true,
      imageBrightness: 100,
      imageContrast: 100,
      imageSaturation: 100,
      imageBlur: 0
    },
    effects: {
      glassmorphism: false,
      frostedGlass: false,
      lightLeak: false,
      duotone: false,
      cinematicBorder: true,
      borderColor: '#b45309',
      borderWidth: 2.5
    },
    createLayers: (verseTa, verseEn, ref, w, h) => [
      {
        id: 'layer-inner-frame',
        name: 'Antique Frame',
        type: 'shape',
        shapeType: 'rounded',
        x: w * 0.07,
        y: h * 0.07,
        width: w * 0.86,
        height: h * 0.86,
        rotation: 0,
        opacity: 0.75,
        visible: true,
        locked: true,
        zIndex: 1,
        fillColor: 'transparent',
        borderColor: '#b45309',
        borderWidth: 1.5,
        borderRadius: 16,
        shadowColor: '#78350f',
        shadowBlur: 12
      },
      {
        id: 'layer-verse-ta',
        name: 'Tamil Verse Text',
        type: 'text',
        role: 'verse-ta',
        text: verseTa || 'வானமும் பூமியும் ஒழிந்துபோம், என் வார்த்தைகளோ ஒழிந்துபோவதில்லை.',
        fontFamily: `'Noto Serif Tamil', Georgia, serif`,
        fontSize: Math.round(w * 0.048),
        fontWeight: '600',
        fontStyle: 'normal',
        textAlign: 'center',
        textColor: '#fef3c7',
        lineHeight: 1.75,
        letterSpacing: 0.4,
        textTransform: 'none',
        shadowColor: 'rgba(0,0,0,0.9)',
        shadowBlur: 10,
        shadowOffsetX: 0,
        shadowOffsetY: 3,
        hasBgBox: false,
        bgBoxColor: '',
        bgBoxPadding: 0,
        bgBoxRadius: 0,
        strokeColor: '',
        strokeWidth: 0,
        x: w * 0.1,
        y: h * 0.3,
        width: w * 0.8,
        height: h * 0.35,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 2
      },
      {
        id: 'layer-verse-en',
        name: 'English Translation',
        type: 'text',
        role: 'verse-en',
        text: verseEn ? `"${verseEn}"` : '"Heaven and earth will pass away, but my words will never pass away."',
        fontFamily: `'Lora', serif`,
        fontSize: Math.round(w * 0.028),
        fontWeight: '400',
        fontStyle: 'italic',
        textAlign: 'center',
        textColor: '#fde68a',
        lineHeight: 1.5,
        letterSpacing: 0.4,
        textTransform: 'none',
        shadowColor: 'rgba(0,0,0,0.8)',
        shadowBlur: 6,
        shadowOffsetX: 0,
        shadowOffsetY: 1,
        hasBgBox: false,
        bgBoxColor: '',
        bgBoxPadding: 0,
        bgBoxRadius: 0,
        strokeColor: '',
        strokeWidth: 0,
        x: w * 0.12,
        y: h * 0.65,
        width: w * 0.76,
        height: h * 0.12,
        rotation: 0,
        opacity: 0.95,
        visible: !!verseEn,
        locked: false,
        zIndex: 3
      },
      {
        id: 'layer-ref',
        name: 'Bible Reference',
        type: 'text',
        role: 'reference',
        text: `• ${ref || 'மத்தேயு 24:35'} •`,
        fontFamily: `'Cinzel', serif`,
        fontSize: Math.round(w * 0.034),
        fontWeight: '700',
        fontStyle: 'normal',
        textAlign: 'center',
        textColor: '#fbbf24',
        lineHeight: 1.3,
        letterSpacing: 2,
        textTransform: 'uppercase',
        shadowColor: 'rgba(180,83,9,0.6)',
        shadowBlur: 8,
        shadowOffsetX: 0,
        shadowOffsetY: 2,
        hasBgBox: false,
        bgBoxColor: '',
        bgBoxPadding: 0,
        bgBoxRadius: 0,
        strokeColor: '',
        strokeWidth: 0,
        x: w * 0.25,
        y: h * 0.79,
        width: w * 0.5,
        height: 44,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 4
      }
    ]
  },

  // 11. Royal Majesty (Imperial Velvet & Gold)
  {
    id: 'royal-majesty',
    name: 'Royal Majesty',
    nameTa: 'ராஜ மஹிமை',
    category: 'Luxury',
    thumbnailGradient: 'linear-gradient(135deg, #1e0938, #581c87, #fbbf24)',
    canvasRatio: '1:1',
    background: {
      type: 'gradient',
      solidColor: '#17062e',
      gradientType: 'linear',
      gradientAngle: 150,
      gradientStops: [
        { offset: 0, color: '#130426' },
        { offset: 0.55, color: '#2e0854' },
        { offset: 1, color: '#4a044e' }
      ],
      overlayColor: '#000000',
      overlayOpacity: 0.15,
      vignette: 45,
      grain: true,
      imageBrightness: 100,
      imageContrast: 100,
      imageSaturation: 100,
      imageBlur: 0
    },
    effects: {
      glassmorphism: true,
      frostedGlass: true,
      lightLeak: true,
      duotone: false,
      cinematicBorder: false,
      borderColor: '#fbbf24',
      borderWidth: 2
    },
    createLayers: (verseTa, verseEn, ref, w, h) => [
      {
        id: 'layer-glass-panel',
        name: 'Imperial Backplate',
        type: 'shape',
        shapeType: 'rounded',
        x: w * 0.08,
        y: h * 0.24,
        width: w * 0.84,
        height: h * 0.56,
        rotation: 0,
        opacity: 0.9,
        visible: true,
        locked: true,
        zIndex: 1,
        fillColor: 'rgba(255, 255, 255, 0.04)',
        borderColor: 'rgba(251, 191, 36, 0.3)',
        borderWidth: 1.5,
        borderRadius: 24,
        shadowColor: 'rgba(88, 28, 135, 0.5)',
        shadowBlur: 24
      },
      {
        id: 'layer-verse-ta',
        name: 'Tamil Verse Text',
        type: 'text',
        role: 'verse-ta',
        text: verseTa || 'கர்த்தர் பெரியவரும் மிகவும் புகழப்படத்தக்கவருமாயிருக்கிறார்; அவருடைய மகத்துவம் ஆராய்ந்து முடியாது.',
        fontFamily: `'Noto Serif Tamil', Georgia, serif`,
        fontSize: Math.round(w * 0.048),
        fontWeight: '600',
        fontStyle: 'normal',
        textAlign: 'center',
        textColor: '#faf5ff',
        lineHeight: 1.75,
        letterSpacing: 0.4,
        textTransform: 'none',
        shadowColor: 'rgba(0,0,0,0.9)',
        shadowBlur: 14,
        shadowOffsetX: 0,
        shadowOffsetY: 3,
        hasBgBox: false,
        bgBoxColor: '',
        bgBoxPadding: 0,
        bgBoxRadius: 0,
        strokeColor: '',
        strokeWidth: 0,
        x: w * 0.1,
        y: h * 0.31,
        width: w * 0.8,
        height: h * 0.32,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 2
      },
      {
        id: 'layer-verse-en',
        name: 'English Translation',
        type: 'text',
        role: 'verse-en',
        text: verseEn ? `"${verseEn}"` : '"Great is the Lord and most worthy of praise; his greatness no one can fathom."',
        fontFamily: `'Cinzel', serif`,
        fontSize: Math.round(w * 0.027),
        fontWeight: '400',
        fontStyle: 'normal',
        textAlign: 'center',
        textColor: '#e9d5ff',
        lineHeight: 1.5,
        letterSpacing: 0.4,
        textTransform: 'none',
        shadowColor: 'rgba(0,0,0,0.7)',
        shadowBlur: 6,
        shadowOffsetX: 0,
        shadowOffsetY: 1,
        hasBgBox: false,
        bgBoxColor: '',
        bgBoxPadding: 0,
        bgBoxRadius: 0,
        strokeColor: '',
        strokeWidth: 0,
        x: w * 0.12,
        y: h * 0.64,
        width: w * 0.76,
        height: h * 0.12,
        rotation: 0,
        opacity: 0.95,
        visible: !!verseEn,
        locked: false,
        zIndex: 3
      },
      {
        id: 'layer-ref',
        name: 'Bible Reference',
        type: 'text',
        role: 'reference',
        text: `👑 ${ref || 'சங்கீதம் 145:3'} 👑`,
        fontFamily: `'Cinzel', serif`,
        fontSize: Math.round(w * 0.034),
        fontWeight: '700',
        fontStyle: 'normal',
        textAlign: 'center',
        textColor: '#fbbf24',
        lineHeight: 1.3,
        letterSpacing: 2,
        textTransform: 'uppercase',
        shadowColor: 'rgba(251,191,36,0.6)',
        shadowBlur: 10,
        shadowOffsetX: 0,
        shadowOffsetY: 2,
        hasBgBox: true,
        bgBoxColor: 'rgba(251, 191, 36, 0.16)',
        bgBoxPadding: 8,
        bgBoxRadius: 99,
        strokeColor: '',
        strokeWidth: 0,
        x: w * 0.25,
        y: h * 0.78,
        width: w * 0.5,
        height: 44,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 4
      }
    ]
  },

  // 12. Modern Editorial (High-Contrast Bold Minimal)
  {
    id: 'modern-editorial',
    name: 'Modern Editorial',
    nameTa: 'நவீன கம்பீரம்',
    category: 'Minimal',
    thumbnailGradient: 'linear-gradient(135deg, #090d16, #1e293b, #f59e0b)',
    canvasRatio: '1:1',
    background: {
      type: 'solid',
      solidColor: '#0b0f19',
      gradientType: 'linear',
      gradientAngle: 180,
      gradientStops: [
        { offset: 0, color: '#090d16' },
        { offset: 1, color: '#111827' }
      ],
      overlayColor: '#000000',
      overlayOpacity: 0,
      vignette: 20,
      grain: false,
      imageBrightness: 100,
      imageContrast: 100,
      imageSaturation: 100,
      imageBlur: 0
    },
    effects: {
      glassmorphism: false,
      frostedGlass: false,
      lightLeak: false,
      duotone: false,
      cinematicBorder: false,
      borderColor: '#f59e0b',
      borderWidth: 0
    },
    createLayers: (verseTa, verseEn, ref, w, h) => [
      {
        id: 'layer-line',
        name: 'Accent Divider',
        type: 'shape',
        shapeType: 'line',
        x: w * 0.44,
        y: h * 0.22,
        width: w * 0.12,
        height: 4,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: true,
        zIndex: 1,
        fillColor: '#f59e0b',
        borderColor: 'transparent',
        borderWidth: 0,
        borderRadius: 99,
        shadowColor: 'rgba(245,158,11,0.5)',
        shadowBlur: 8
      },
      {
        id: 'layer-verse-ta',
        name: 'Tamil Verse Text',
        type: 'text',
        role: 'verse-ta',
        text: verseTa || 'விசுவாசத்தினாலே நீதிமான் பிழைப்பான்; பின்வாங்கிப்போவானானால் அவன்மேல் என் ஆத்துமா பிரியமாயிராது.',
        fontFamily: `'Noto Sans Tamil', Inter, sans-serif`,
        fontSize: Math.round(w * 0.05),
        fontWeight: '700',
        fontStyle: 'normal',
        textAlign: 'center',
        textColor: '#ffffff',
        lineHeight: 1.7,
        letterSpacing: 0.2,
        textTransform: 'none',
        shadowColor: 'rgba(0,0,0,0.8)',
        shadowBlur: 10,
        shadowOffsetX: 0,
        shadowOffsetY: 2,
        hasBgBox: false,
        bgBoxColor: '',
        bgBoxPadding: 0,
        bgBoxRadius: 0,
        strokeColor: '',
        strokeWidth: 0,
        x: w * 0.1,
        y: h * 0.32,
        width: w * 0.8,
        height: h * 0.35,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 2
      },
      {
        id: 'layer-verse-en',
        name: 'English Translation',
        type: 'text',
        role: 'verse-en',
        text: verseEn ? `"${verseEn}"` : '"The righteous shall live by faith, and if he shrinks back, my soul has no pleasure in him."',
        fontFamily: `'Inter', sans-serif`,
        fontSize: Math.round(w * 0.027),
        fontWeight: '500',
        fontStyle: 'normal',
        textAlign: 'center',
        textColor: '#cbd5e1',
        lineHeight: 1.5,
        letterSpacing: 0.3,
        textTransform: 'none',
        shadowColor: 'rgba(0,0,0,0.6)',
        shadowBlur: 6,
        shadowOffsetX: 0,
        shadowOffsetY: 1,
        hasBgBox: false,
        bgBoxColor: '',
        bgBoxPadding: 0,
        bgBoxRadius: 0,
        strokeColor: '',
        strokeWidth: 0,
        x: w * 0.12,
        y: h * 0.66,
        width: w * 0.76,
        height: h * 0.12,
        rotation: 0,
        opacity: 0.95,
        visible: !!verseEn,
        locked: false,
        zIndex: 3
      },
      {
        id: 'layer-ref',
        name: 'Bible Reference',
        type: 'text',
        role: 'reference',
        text: `— ${ref || 'எபிரெயர் 10:38'} —`,
        fontFamily: `'Inter', sans-serif`,
        fontSize: Math.round(w * 0.03),
        fontWeight: '700',
        fontStyle: 'normal',
        textAlign: 'center',
        textColor: '#f59e0b',
        lineHeight: 1.3,
        letterSpacing: 2,
        textTransform: 'uppercase',
        shadowColor: 'transparent',
        shadowBlur: 0,
        shadowOffsetX: 0,
        shadowOffsetY: 0,
        hasBgBox: false,
        bgBoxColor: '',
        bgBoxPadding: 0,
        bgBoxRadius: 0,
        strokeColor: '',
        strokeWidth: 0,
        x: w * 0.25,
        y: h * 0.8,
        width: w * 0.5,
        height: 40,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 4
      }
    ]
  },

  // 13. Celestial Radiance (வானக சிலுவை - Cobalt Blue & Gold Radiance)
  {
    id: 'celestial-cross',
    name: 'Celestial Radiance',
    nameTa: 'வானக சிலுவை',
    category: 'Luxury',
    thumbnailGradient: 'linear-gradient(135deg, #091a3e, #1e3a8a, #38bdf8)',
    canvasRatio: '1:1',
    background: {
      type: 'gradient',
      solidColor: '#070e24',
      gradientType: 'radial',
      gradientAngle: 0,
      gradientStops: [
        { offset: 0, color: '#162b66' },
        { offset: 0.65, color: '#09153a' },
        { offset: 1, color: '#030817' }
      ],
      overlayColor: '#000000',
      overlayOpacity: 0.25,
      vignette: 50,
      grain: true,
      imageBrightness: 100,
      imageContrast: 100,
      imageSaturation: 100,
      imageBlur: 0
    },
    effects: {
      glassmorphism: true,
      frostedGlass: false,
      lightLeak: true,
      duotone: false,
      cinematicBorder: true,
      borderColor: '#38bdf8',
      borderWidth: 2
    },
    createLayers: (verseTa, verseEn, ref, w, h) => [
      {
        id: 'layer-frame',
        name: 'Celestial Border',
        type: 'shape',
        shapeType: 'rounded',
        x: w * 0.05,
        y: h * 0.05,
        width: w * 0.9,
        height: h * 0.9,
        rotation: 0,
        opacity: 0.7,
        visible: true,
        locked: true,
        zIndex: 1,
        fillColor: 'transparent',
        borderColor: '#38bdf8',
        borderWidth: 1.5,
        borderRadius: 24,
        shadowColor: 'rgba(56, 189, 248, 0.4)',
        shadowBlur: 14
      },
      {
        id: 'layer-cross',
        name: 'Radiant Cross',
        type: 'element',
        elementId: 'cross-ornate',
        svgPath: 'M12 2v20M7 8h10',
        x: w * 0.5 - 20,
        y: h * 0.14,
        width: 40,
        height: 48,
        rotation: 0,
        opacity: 0.9,
        visible: true,
        locked: false,
        zIndex: 2,
        color: '#38bdf8',
        shadowColor: 'rgba(56, 189, 248, 0.8)',
        shadowBlur: 16
      },
      {
        id: 'layer-verse-ta',
        name: 'Tamil Verse Text',
        type: 'text',
        role: 'verse-ta',
        text: verseTa || 'வானங்கள் தேவனுடைய மகிமையை வெளிப்படுத்துகிறது, ஆகாயவிரிவு அவருடைய கரங்களின் கிரியையை அறிவிக்கிறது.',
        fontFamily: `'Noto Serif Tamil', Georgia, serif`,
        fontSize: Math.round(w * 0.046),
        fontWeight: '600',
        fontStyle: 'normal',
        textAlign: 'center',
        textColor: '#f0f9ff',
        lineHeight: 1.7,
        letterSpacing: 0.2,
        textTransform: 'none',
        shadowColor: 'rgba(0,0,0,0.85)',
        shadowBlur: 14,
        shadowOffsetX: 0,
        shadowOffsetY: 2,
        hasBgBox: false,
        bgBoxColor: '',
        bgBoxPadding: 0,
        bgBoxRadius: 0,
        strokeColor: '',
        strokeWidth: 0,
        x: w * 0.08,
        y: h * 0.32,
        width: w * 0.84,
        height: h * 0.35,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 3
      },
      {
        id: 'layer-verse-en',
        name: 'English Translation',
        type: 'text',
        role: 'verse-en',
        text: verseEn ? `"${verseEn}"` : '"The heavens declare the glory of God, and the sky above proclaims his handiwork."',
        fontFamily: `'Cinzel', Georgia, serif`,
        fontSize: Math.round(w * 0.026),
        fontWeight: '500',
        fontStyle: 'normal',
        textAlign: 'center',
        textColor: '#bae6fd',
        lineHeight: 1.5,
        letterSpacing: 0.4,
        textTransform: 'none',
        shadowColor: 'rgba(0,0,0,0.6)',
        shadowBlur: 8,
        shadowOffsetX: 0,
        shadowOffsetY: 1,
        hasBgBox: false,
        bgBoxColor: '',
        bgBoxPadding: 0,
        bgBoxRadius: 0,
        strokeColor: '',
        strokeWidth: 0,
        x: w * 0.1,
        y: h * 0.67,
        width: w * 0.8,
        height: h * 0.12,
        rotation: 0,
        opacity: 0.95,
        visible: !!verseEn,
        locked: false,
        zIndex: 4
      },
      {
        id: 'layer-ref',
        name: 'Bible Reference',
        type: 'text',
        role: 'reference',
        text: `— ${ref || 'சங்கீதம் 19:1'} —`,
        fontFamily: `'Cinzel', Georgia, serif`,
        fontSize: Math.round(w * 0.028),
        fontWeight: '700',
        fontStyle: 'normal',
        textAlign: 'center',
        textColor: '#38bdf8',
        lineHeight: 1.3,
        letterSpacing: 2.5,
        textTransform: 'uppercase',
        shadowColor: 'rgba(56, 189, 248, 0.4)',
        shadowBlur: 6,
        shadowOffsetX: 0,
        shadowOffsetY: 0,
        hasBgBox: false,
        bgBoxColor: '',
        bgBoxPadding: 0,
        bgBoxRadius: 0,
        strokeColor: '',
        strokeWidth: 0,
        x: w * 0.2,
        y: h * 0.81,
        width: w * 0.6,
        height: 40,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 5
      }
    ]
  },

  // 14. Mount Zion (சீயோன் பர்வதம் - Majestic Forest & Living Emerald)
  {
    id: 'mount-zion',
    name: 'Mount Zion',
    nameTa: 'சீயோன் பர்வதம்',
    category: 'Nature',
    thumbnailGradient: 'linear-gradient(135deg, #062419, #0f5132, #10b981)',
    canvasRatio: '1:1',
    background: {
      type: 'gradient',
      solidColor: '#041c14',
      gradientType: 'linear',
      gradientAngle: 155,
      gradientStops: [
        { offset: 0, color: '#031710' },
        { offset: 0.5, color: '#093627' },
        { offset: 1, color: '#02120c' }
      ],
      overlayColor: '#000000',
      overlayOpacity: 0.2,
      vignette: 45,
      grain: true,
      imageBrightness: 100,
      imageContrast: 100,
      imageSaturation: 100,
      imageBlur: 0
    },
    effects: {
      glassmorphism: true,
      frostedGlass: false,
      lightLeak: false,
      duotone: false,
      cinematicBorder: true,
      borderColor: '#10b981',
      borderWidth: 2
    },
    createLayers: (verseTa, verseEn, ref, w, h) => [
      {
        id: 'layer-frame',
        name: 'Emerald Frame',
        type: 'shape',
        shapeType: 'rounded',
        x: w * 0.05,
        y: h * 0.05,
        width: w * 0.9,
        height: h * 0.9,
        rotation: 0,
        opacity: 0.65,
        visible: true,
        locked: true,
        zIndex: 1,
        fillColor: 'transparent',
        borderColor: '#10b981',
        borderWidth: 1.5,
        borderRadius: 22,
        shadowColor: 'rgba(16, 185, 129, 0.4)',
        shadowBlur: 12
      },
      {
        id: 'layer-symbol',
        name: 'Olive Dove',
        type: 'element',
        elementId: 'dove-peace',
        svgPath: 'M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-1 14.5v-9l6 4.5-6 4.5z',
        x: w * 0.5 - 20,
        y: h * 0.14,
        width: 40,
        height: 40,
        rotation: 0,
        opacity: 0.85,
        visible: true,
        locked: false,
        zIndex: 2,
        color: '#34d399',
        shadowColor: 'rgba(52, 211, 153, 0.6)',
        shadowBlur: 12
      },
      {
        id: 'layer-verse-ta',
        name: 'Tamil Verse Text',
        type: 'text',
        role: 'verse-ta',
        text: verseTa || 'கர்த்தரை நம்புகிறவர்கள் என்றென்றைக்கும் அசையாமல் நிலைத்திருக்கும் சீயோன் பர்வதத்தைப் போலிருப்பார்கள்.',
        fontFamily: `'Mukta Malar', 'Noto Sans Tamil', sans-serif`,
        fontSize: Math.round(w * 0.046),
        fontWeight: '600',
        fontStyle: 'normal',
        textAlign: 'center',
        textColor: '#ecfdf5',
        lineHeight: 1.7,
        letterSpacing: 0.2,
        textTransform: 'none',
        shadowColor: 'rgba(0,0,0,0.85)',
        shadowBlur: 14,
        shadowOffsetX: 0,
        shadowOffsetY: 2,
        hasBgBox: false,
        bgBoxColor: '',
        bgBoxPadding: 0,
        bgBoxRadius: 0,
        strokeColor: '',
        strokeWidth: 0,
        x: w * 0.08,
        y: h * 0.32,
        width: w * 0.84,
        height: h * 0.35,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 3
      },
      {
        id: 'layer-verse-en',
        name: 'English Translation',
        type: 'text',
        role: 'verse-en',
        text: verseEn ? `"${verseEn}"` : '"Those who trust in the Lord are like Mount Zion, which cannot be moved, but abides forever."',
        fontFamily: `'Lora', serif`,
        fontSize: Math.round(w * 0.026),
        fontWeight: '500',
        fontStyle: 'normal',
        textAlign: 'center',
        textColor: '#a7f3d0',
        lineHeight: 1.5,
        letterSpacing: 0.3,
        textTransform: 'none',
        shadowColor: 'rgba(0,0,0,0.6)',
        shadowBlur: 8,
        shadowOffsetX: 0,
        shadowOffsetY: 1,
        hasBgBox: false,
        bgBoxColor: '',
        bgBoxPadding: 0,
        bgBoxRadius: 0,
        strokeColor: '',
        strokeWidth: 0,
        x: w * 0.1,
        y: h * 0.67,
        width: w * 0.8,
        height: h * 0.12,
        rotation: 0,
        opacity: 0.95,
        visible: !!verseEn,
        locked: false,
        zIndex: 4
      },
      {
        id: 'layer-ref',
        name: 'Bible Reference',
        type: 'text',
        role: 'reference',
        text: `— ${ref || 'சங்கீதம் 125:1'} —`,
        fontFamily: `'Lora', serif`,
        fontSize: Math.round(w * 0.028),
        fontWeight: '700',
        fontStyle: 'normal',
        textAlign: 'center',
        textColor: '#34d399',
        lineHeight: 1.3,
        letterSpacing: 2,
        textTransform: 'uppercase',
        shadowColor: 'transparent',
        shadowBlur: 0,
        shadowOffsetX: 0,
        shadowOffsetY: 0,
        hasBgBox: false,
        bgBoxColor: '',
        bgBoxPadding: 0,
        bgBoxRadius: 0,
        strokeColor: '',
        strokeWidth: 0,
        x: w * 0.2,
        y: h * 0.81,
        width: w * 0.6,
        height: 40,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 5
      }
    ]
  },

  // 15. Shepherd Valley (நல்மேய்ப்பன் - Soft Lavender & Velvet Peace)
  {
    id: 'shepherd-valley',
    name: 'Shepherd Valley',
    nameTa: 'நல்மேய்ப்பன்',
    category: 'Serene',
    thumbnailGradient: 'linear-gradient(135deg, #1e1136, #3b1d6e, #a855f7)',
    canvasRatio: '1:1',
    background: {
      type: 'gradient',
      solidColor: '#120924',
      gradientType: 'linear',
      gradientAngle: 140,
      gradientStops: [
        { offset: 0, color: '#0d051c' },
        { offset: 0.55, color: '#26114a' },
        { offset: 1, color: '#130728' }
      ],
      overlayColor: '#000000',
      overlayOpacity: 0.2,
      vignette: 45,
      grain: true,
      imageBrightness: 100,
      imageContrast: 100,
      imageSaturation: 100,
      imageBlur: 0
    },
    effects: {
      glassmorphism: true,
      frostedGlass: false,
      lightLeak: true,
      duotone: false,
      cinematicBorder: true,
      borderColor: '#c084fc',
      borderWidth: 2
    },
    createLayers: (verseTa, verseEn, ref, w, h) => [
      {
        id: 'layer-frame',
        name: 'Lavender Frame',
        type: 'shape',
        shapeType: 'rounded',
        x: w * 0.05,
        y: h * 0.05,
        width: w * 0.9,
        height: h * 0.9,
        rotation: 0,
        opacity: 0.65,
        visible: true,
        locked: true,
        zIndex: 1,
        fillColor: 'transparent',
        borderColor: '#c084fc',
        borderWidth: 1.5,
        borderRadius: 22,
        shadowColor: 'rgba(192, 132, 252, 0.4)',
        shadowBlur: 14
      },
      {
        id: 'layer-symbol',
        name: 'Sacred Heart / Cross',
        type: 'element',
        elementId: 'cross-simple',
        svgPath: 'M12 2v20M5 8h14',
        x: w * 0.5 - 18,
        y: h * 0.14,
        width: 36,
        height: 44,
        rotation: 0,
        opacity: 0.85,
        visible: true,
        locked: false,
        zIndex: 2,
        color: '#c084fc',
        shadowColor: 'rgba(192, 132, 252, 0.7)',
        shadowBlur: 14
      },
      {
        id: 'layer-verse-ta',
        name: 'Tamil Verse Text',
        type: 'text',
        role: 'verse-ta',
        text: verseTa || 'கர்த்தர் என் மேய்ப்பராயிருக்கிறார்; நான் தாழ்ச்சியடையேன். அவர் என்னைப் புல்லுள்ள இடங்களில் மேய்க்கிறார்.',
        fontFamily: `'Arima', cursive`,
        fontSize: Math.round(w * 0.048),
        fontWeight: '700',
        fontStyle: 'normal',
        textAlign: 'center',
        textColor: '#faf5ff',
        lineHeight: 1.7,
        letterSpacing: 0.2,
        textTransform: 'none',
        shadowColor: 'rgba(0,0,0,0.85)',
        shadowBlur: 14,
        shadowOffsetX: 0,
        shadowOffsetY: 2,
        hasBgBox: false,
        bgBoxColor: '',
        bgBoxPadding: 0,
        bgBoxRadius: 0,
        strokeColor: '',
        strokeWidth: 0,
        x: w * 0.08,
        y: h * 0.32,
        width: w * 0.84,
        height: h * 0.35,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 3
      },
      {
        id: 'layer-verse-en',
        name: 'English Translation',
        type: 'text',
        role: 'verse-en',
        text: verseEn ? `"${verseEn}"` : '"The Lord is my shepherd; I shall not want. He makes me lie down in green pastures."',
        fontFamily: `'Playfair Display', Georgia, serif`,
        fontSize: Math.round(w * 0.026),
        fontWeight: '500',
        fontStyle: 'normal',
        textAlign: 'center',
        textColor: '#e9d5ff',
        lineHeight: 1.5,
        letterSpacing: 0.3,
        textTransform: 'none',
        shadowColor: 'rgba(0,0,0,0.6)',
        shadowBlur: 8,
        shadowOffsetX: 0,
        shadowOffsetY: 1,
        hasBgBox: false,
        bgBoxColor: '',
        bgBoxPadding: 0,
        bgBoxRadius: 0,
        strokeColor: '',
        strokeWidth: 0,
        x: w * 0.1,
        y: h * 0.67,
        width: w * 0.8,
        height: h * 0.12,
        rotation: 0,
        opacity: 0.95,
        visible: !!verseEn,
        locked: false,
        zIndex: 4
      },
      {
        id: 'layer-ref',
        name: 'Bible Reference',
        type: 'text',
        role: 'reference',
        text: `— ${ref || 'சங்கீதம் 23:1-2'} —`,
        fontFamily: `'Playfair Display', Georgia, serif`,
        fontSize: Math.round(w * 0.028),
        fontWeight: '700',
        fontStyle: 'normal',
        textAlign: 'center',
        textColor: '#c084fc',
        lineHeight: 1.3,
        letterSpacing: 2,
        textTransform: 'uppercase',
        shadowColor: 'transparent',
        shadowBlur: 0,
        shadowOffsetX: 0,
        shadowOffsetY: 0,
        hasBgBox: false,
        bgBoxColor: '',
        bgBoxPadding: 0,
        bgBoxRadius: 0,
        strokeColor: '',
        strokeWidth: 0,
        x: w * 0.2,
        y: h * 0.81,
        width: w * 0.6,
        height: 40,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 5
      }
    ]
  },

  // 16. Fiery Covenant (அக்கினி உடன்படிக்கை - Crimson Flame & Holy Fire)
  {
    id: 'fiery-covenant',
    name: 'Fiery Covenant',
    nameTa: 'அக்கினி உடன்படிக்கை',
    category: 'Warm',
    thumbnailGradient: 'linear-gradient(135deg, #2b0c0c, #7f1d1d, #ef4444)',
    canvasRatio: '1:1',
    background: {
      type: 'gradient',
      solidColor: '#1a0505',
      gradientType: 'radial',
      gradientAngle: 0,
      gradientStops: [
        { offset: 0, color: '#4a1111' },
        { offset: 0.65, color: '#240808' },
        { offset: 1, color: '#0d0202' }
      ],
      overlayColor: '#000000',
      overlayOpacity: 0.2,
      vignette: 55,
      grain: true,
      imageBrightness: 100,
      imageContrast: 100,
      imageSaturation: 100,
      imageBlur: 0
    },
    effects: {
      glassmorphism: true,
      frostedGlass: false,
      lightLeak: true,
      duotone: false,
      cinematicBorder: true,
      borderColor: '#f87171',
      borderWidth: 2
    },
    createLayers: (verseTa, verseEn, ref, w, h) => [
      {
        id: 'layer-frame',
        name: 'Crimson Frame',
        type: 'shape',
        shapeType: 'rounded',
        x: w * 0.05,
        y: h * 0.05,
        width: w * 0.9,
        height: h * 0.9,
        rotation: 0,
        opacity: 0.7,
        visible: true,
        locked: true,
        zIndex: 1,
        fillColor: 'transparent',
        borderColor: '#f87171',
        borderWidth: 1.5,
        borderRadius: 22,
        shadowColor: 'rgba(248, 113, 113, 0.45)',
        shadowBlur: 14
      },
      {
        id: 'layer-symbol',
        name: 'Sacred Flame Cross',
        type: 'element',
        elementId: 'cross-radiant',
        svgPath: 'M12 2v20M5 9h14M12 6a6 6 0 0 1 0 12',
        x: w * 0.5 - 20,
        y: h * 0.14,
        width: 40,
        height: 48,
        rotation: 0,
        opacity: 0.9,
        visible: true,
        locked: false,
        zIndex: 2,
        color: '#f87171',
        shadowColor: 'rgba(248, 113, 113, 0.8)',
        shadowBlur: 16
      },
      {
        id: 'layer-verse-ta',
        name: 'Tamil Verse Text',
        type: 'text',
        role: 'verse-ta',
        text: verseTa || 'நம்முடைய தேவன் பட்சிக்கிற அக்கினியாயிருக்கிறாரே.',
        fontFamily: `'Baloo Thambi 2', 'Noto Sans Tamil', sans-serif`,
        fontSize: Math.round(w * 0.052),
        fontWeight: '700',
        fontStyle: 'normal',
        textAlign: 'center',
        textColor: '#fef2f2',
        lineHeight: 1.6,
        letterSpacing: 0.2,
        textTransform: 'none',
        shadowColor: 'rgba(0,0,0,0.85)',
        shadowBlur: 14,
        shadowOffsetX: 0,
        shadowOffsetY: 2,
        hasBgBox: false,
        bgBoxColor: '',
        bgBoxPadding: 0,
        bgBoxRadius: 0,
        strokeColor: '',
        strokeWidth: 0,
        x: w * 0.08,
        y: h * 0.33,
        width: w * 0.84,
        height: h * 0.35,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 3
      },
      {
        id: 'layer-verse-en',
        name: 'English Translation',
        type: 'text',
        role: 'verse-en',
        text: verseEn ? `"${verseEn}"` : '"For our God is a consuming fire."',
        fontFamily: `'Poppins', sans-serif`,
        fontSize: Math.round(w * 0.028),
        fontWeight: '600',
        fontStyle: 'normal',
        textAlign: 'center',
        textColor: '#fecaca',
        lineHeight: 1.5,
        letterSpacing: 0.3,
        textTransform: 'none',
        shadowColor: 'rgba(0,0,0,0.6)',
        shadowBlur: 8,
        shadowOffsetX: 0,
        shadowOffsetY: 1,
        hasBgBox: false,
        bgBoxColor: '',
        bgBoxPadding: 0,
        bgBoxRadius: 0,
        strokeColor: '',
        strokeWidth: 0,
        x: w * 0.1,
        y: h * 0.67,
        width: w * 0.8,
        height: h * 0.12,
        rotation: 0,
        opacity: 0.95,
        visible: !!verseEn,
        locked: false,
        zIndex: 4
      },
      {
        id: 'layer-ref',
        name: 'Bible Reference',
        type: 'text',
        role: 'reference',
        text: `— ${ref || 'எபிரெயர் 12:29'} —`,
        fontFamily: `'Poppins', sans-serif`,
        fontSize: Math.round(w * 0.028),
        fontWeight: '700',
        fontStyle: 'normal',
        textAlign: 'center',
        textColor: '#f87171',
        lineHeight: 1.3,
        letterSpacing: 2,
        textTransform: 'uppercase',
        shadowColor: 'transparent',
        shadowBlur: 0,
        shadowOffsetX: 0,
        shadowOffsetY: 0,
        hasBgBox: false,
        bgBoxColor: '',
        bgBoxPadding: 0,
        bgBoxRadius: 0,
        strokeColor: '',
        strokeWidth: 0,
        x: w * 0.2,
        y: h * 0.81,
        width: w * 0.6,
        height: 40,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        zIndex: 5
      }
    ]
  }
];

export const CANVAS_SIZES = CANVAS_PRESETS;
export const TAMIL_FONTS = TAMIL_FONTS_LIST.map(f => ({ family: f.name, name: f.name, nameTa: f.nameTa, category: 'Tamil' }));
export const ENGLISH_FONTS = ENGLISH_FONTS_LIST.map(f => ({ family: f.name, name: f.name, nameTa: f.nameTa, category: 'English' }));
